- .gitignore
- litex_boards/partner/platforms/fomu_evt.py
- litex_boards/partner/targets/fomu.py
This adds a "fomu" target, which currently mostly involves the CRG.
Separately, is up5kspram available anywhere except litex-buildenv and https://github.com/xobs/lxsocsupport/blob/master/lxsocsupport/up5kspram.py ?
> Add fomu target

- litex_boards/community/targets/ecp5_evn.py
The system clock was driven directly while it should be driven by the PLL. I somehow forgot to remove this line before the initial PR.
> Fix ecp5_evn clock

- litex_boards/partner/targets/fomu.py
This adds the Fomu target back in.  The default BaseSoC supports
various USB methods, and will be updated as more become available.
The debug bridge may optionally be added.
Signed-off-by: Sean Cross <sean@xobs.io>
> partner: add fomu target

- litex_boards/partner/platforms/fomu_evt.py
- litex_boards/partner/targets/fomu.py
This makes some minor changes to the Fomu target, allowing for the use of `fomu` with a CPU and an interrupt source on the USB module.
> Fomu cpu updates

- litex_boards/partner/targets/ulx3s.py
Allows setting system clock frequency via command-line argument.  Uses the same code/method as the versa-ecp5 target.  This is useful when building rocket synthesis doesn't pass the default timing of 50mhz.
> add sys clock freq flag, uses same method as current versa code

- litex_boards/partner/targets/aller.py
- litex_boards/partner/targets/nereid.py
- litex_boards/partner/targets/tagus.py
Commit https://github.com/enjoy-digital/litex/commit/8be5824e258b84df240d34636aaa539124b92c65 simplified the handling of csr regions and constants. These target files need to be updated to the new API.
They also still use the `with_shadow_base` parameter to `get_csr_header` which was removed/deprecated in https://github.com/enjoy-digital/litex/commit/a4ef9b29b9781f576caba316c7920c902a8d8c8f. I'm nearly positive that the new default behavior matches the previous behavior that the Numato targets were using.
Longer discussion in https://github.com/litex-hub/litex-boards/issues/25
> Fix numato csr headers

- litex_boards/partner/platforms/hadbadge.py
- litex_boards/partner/targets/hadbadge.py
Add the [Hackaday Supercon 2019 badge](https://hackaday.io/project/167255-2019-hackaday-superconference-badge) which has an ECP5 FPGA.
These changes are from [a fork](https://github.com/mwelling/litex-boards) by Michael Welling (@mwelling)
During Supercon, we tried two approaches:
- use the built-in 16MB QSPI SRAM
- use add-on cartiridge with 32MB SDRAM by Jacob Creedon
We were not able to get the QSPI SRAM working so I've removed those changes, and I have just added the changes that are needed to boot Linux with the 32MB SDRAM.
In addition to @mwelling, thank you to Jacob Creedon (@jcreedon), @GregDavill, Tim Ansell (@mithro), and Sean Cross (@xobs) who all helped get Linux working on this badge.
KiCad design files by @jcreedon for the SDRAM cartridge are [available on …
> add the Hackaday Supercon ECP5 badge

- litex_boards/community/platforms/kx2.py
- litex_boards/community/targets/kx2.py
This PR adds support for the enclustra KX2 board including DDR3 Memory support as specified here:
https://www.enclustra.com/en/products/fpga-modules/mercury-kx2/
> ADD: KX2 and DDR3 support

- litex_boards/community/platforms/mimas_a7.py
- litex_boards/community/targets/mimas_a7.py
This PR adds basic platform constraints and LiteX `BaseSoc` and `EthernetSoC` target files for the Numato Lab Mimas A7 FPGA development board. Not all of the board's constraints are mapped over yet, but this is good chunk of them. Ethernet has not been tested yet.
> Add Mimas A7 board support

- litex_boards/platforms/colorlight_5a_75b.py
Fix two SDRAM pins:
- SDRAM clock is C6 not B9 (used for DQ7)
- typo in chubby75 repo take A4 connected to C1 instead of C12.
Tested with memtest
> platforms/colorlight_5a_75b.py: fix sdram_clock and sdram a pins

- litex_boards/platforms/zcu104.py
- litex_boards/targets/zcu104.py
This adds basic support for the ZCU104 board, DDR4 configuration is currently untested.
> Add support for ZCU104 board

- litex_boards/platforms/icebreaker.py
- litex_boards/targets/icebreaker.py
This patch set adds the iCE40UP5k iCEBreaker FPGA development board support.
The target script currently has the bios supported as we need to remap the ROM position in the linker script so we can place the bios in the SPI FLASH. But it definitely works and we can write our own programs to run on the resulting SOC.
You can find an exmaple blinky application here: https://github.com/icebreaker-fpga/icebreaker-litex-examples
> Add iCEBreaker FPGA support

- litex_boards/platforms/mercury_xu5.py
- litex_boards/targets/mercury_xu5.py
This PR would add support for Enclustra [Mercury XU5](https://www.enclustra.com/en/products/system-on-chip-modules/mercury-xu5/) board (specifically I'm testing on [Mercury PE1](https://www.enclustra.com/en/products/base-boards/mercury-pe1-200-300-400/)).
I've tried to match the IO settings from Xilinx's MIG, but read leveling fails, so it is a WIP.
Current output I'm getting:
```
Initializing SDRAM...
SDRAM now under software control
Write leveling:
m0: |000000001111111111111| delay: 127
m1: |000000000111111111111| delay: 131
Read leveling:
m0, b0: |00000000000000000000000000000000| delays: -
m0, b1: |00000000000000000000000000000000| delays: -
m0, b2: |00000000000000000000000000000000| delays: -
m0, b3: |00000000000000000000000000000000| …
```
> add Enclustra Mercury XU5 board

- litex_boards/platforms/de10nano.py
- litex_boards/targets/de10nano.py
The de10nano in a MiSTer setup has a secondary sd card attached to gpio pins. This patch, along with proposed patches to the litex bios allow the loading of the Linux images from this secondary sd card, partition 1 formatted as a FAT16 partition.
> de10nano add in support for MiSTer secondary sd card

- litex_boards/platforms/trellisboard.py
- litex_boards/targets/trellisboard.py
@enjoy-digital: this, unlike my earlier LiteSDCard based PR **works** -- successfully booted a boot.bin (bbl blob containing kernel and busybox) on the trellisboard. Please review and pull!
Thanks,
--G
> Move trellisboard target to SoCCore, add SPI-mode SDCard support

- litex_boards/platforms/zcu104.py
- litex_boards/targets/zcu104.py
Depends on enjoy-digital/litedram#172
This PR adds fully working 64-bit SO-DIMM config for ZCU104 that was tested in #49
> zcu104: add fully working SO-DIMM config

- litex_boards/platforms/colorlight_5a_75b.py
- litex_boards/targets/colorlight_5a_75b.py
Things done:
- Add `ba` pin for v6.1, since it won't build otherwise. According to the datasheet, A11 is the bank activate pin. Memtest is ok.
- Add eth_clocks 1. Simply used the pins documented in the chubby75 repo.
Also added serial pins, similar to v7.0. At 115200 baud, there was some strange behavior on the rx pin & it's loopback output, which I suspect may have to do with the capacitor that seems to be connected to the button. I changed the baud rate for the example to 9600 baud, since that works (for me).
> Improve compatability with colorlight 5a-75b v6.1

- litex_boards/targets/orangecrab.py
The parsed args are stripped off by soc_core_argdict() (called from
soc_sdram_argdict() so we have to pass them explicitly (or pass the
original "args", but this mimics the rest of the code in the repo).
This fixes #72
> targets/orangecrab.py: propagate command arguments

- litex_boards/targets/nexys4ddr.py
this already exists and has been pretty thoroughly tested in the `litex/boards/targets` version
> platforms/nexys4ddr: add option to build with spi-mode sdcard support

- litex_boards/platforms/pano_logic_g2.py
- litex_boards/targets/pano_logic_g2.py
Without this change the terminal baud rate is 23,941 (measured by a scope) since the default clock is 25 Mhz instead of the expected 125 Mhz.  
The master clock on the Pano comes from the Ethernet PHY which is normally 125Mhz, but it is 25 Mhz while the PHY is in reset.  The active low reset pin is driven by FPGA pin R11. 
See https://github.com/tomverbeure/panologic-g2#fpga-external-clocking-architecture
> Take Ethernet PHY out of reset so default clock is 125 Mhz

- litex_boards/platforms/zcu104.py
- litex_boards/targets/zcu104.py
This adds I2C for the ZCU104 board, to be able to read SPD EEPROM from SO-DIMM modules.
> ZCU104: add I2C

- litex_boards/platforms/versa_ecp5.py
- litex_boards/targets/versa_ecp5.py
Verified to compile and load on a POWER system with the ECP5 Versa (non-5G) variant when `--device=LFE5UM-45F-8BG381C` is passed to ` ./versa_ecp5.py`
> Fix Microwatt on Versa board

- litex_boards/platforms/arty.py
This moves mappings of external SDCard Pmod to port JD, making it compatible with the the [Arty expansion board by Antmicro](https://github.com/antmicro/arty-expansion-board).
> Change sdcard Pmod from JB to JD

- litex_boards/platforms/logicbone.py
- litex_boards/targets/logicbone.py
This adds the platform and target files for an ECP5-based development board that I have been designing in my spare time, and it's more or less a Beaglebone clone using an ECP5 in place of the typical SoC. The design files for the project can be found at https://github.com/oskirby/logicbone
So far, I have been able to get it to boot into Linux using the linux-on-litex-vexriscv project and I have tested out the DDR3 memory interface, USB and Ethernet peripherals.
It could still be considered a WIP as I have encountered a few bugs in the process, though I am still trying to figure out if they are hardware or software problems.
- Enabling "spisdcard" slot results in a kernel panic.
- DDR3 memory occasionally fails memtest.
- Configuring for 2GB of memory causes memtest to fail.
> Add Logicbone ECP5 board

- litex_boards/platforms/orangecrab.py
I was building the foboot bootloader for both r0.2 and r0.1 boards, and realised that I was missing some io definitions on the r0.1 variants.
They're now updated. 
Along with fixing the standard extensions.
Changing the VID/PID pair from the fomu to our own: http://pid.codes/1209/5AF0/
> OrangeCrab: Update platform

- litex_boards/platforms/de10nano.py
- litex_boards/targets/de10nano.py
Add Misc("") tags, provides stability for the SDRAM to allow use of HalfRateGENSDRPHY
> Enable use of HalfRateGENSDRPHY on de10nano

- litex_boards/platforms/ulx3s.py
- litex_boards/targets/ulx3s.py
The ULX3S comes with a dedicated header where the user can plug in a SSD1331 or SSD1306 OLED display panel. So while not a built-in part of the board, these pins are definitely specifically for this display. They are also present in the official lpf: https://github.com/emard/ulx3s/blob/master/doc/constraints/ulx3s_v20.lpf
I made the choice to use the SPI mode of the display, rather than the less common I2C mode. In particular since LiteX does not come with an official I2C core, I think this is a defensible choice.
I am not 100% sure if the way I split the pins for the SPI and GPIO lines is idiomatic, but it is convenient. I think the way I faked the MISO is a bit ugly, but not too bad. I chose not to include the CS pin with the SPI pins because as far as I can tell it just becomes a …
> Add optional OLED peripheral to ULX3S target

- litex_boards/platforms/arty.py
This makes it compatible with the Arty A7 expansion board by Antmicro
(https://github.com/antmicro/arty-expansion-board).
> arty: Change USB-uart and I2S Pmod configuration

- litex_boards/platforms/alveo_u250.py
- litex_boards/targets/alveo_u250.py
Based on the implementation in xcu1525.
Note that enjoy-digital/litepcie#39 needs to be fixed before this builds out-of-the-box.
scratch_test seems to work correctly:
```
$ ./litepcie_util scratch_test
Write 0x12345678 to scratch register:
Read: 0x12345678
Write 0xdeadbeef to scratch register:
Read: 0xdeadbeef
```
I haven't tested any further than that. I also found I needed to reboot for the device to appear correctly, but my setup is somewhat unusual as it involves Thunderbolt on a X399 motherboard without the proper BIOS support.
> alveo_u250: Add PCIe x4 support

- litex_boards/platforms/orangecrab.py
On r0.1, all three user_leds are mapped to the same pin.
Fix this by mapping them to the pins connected to the individual
channels of the RGB LED, to match the comments, the schematics, and the
spirit of r0.2.
Untested on real hardware (I have r0.2 only).
Fixes: c94cbae0c04bbda3 ("orangecrab: add user_led (RGB leds), DFUProg and --load support.")
Signed-off-by: Geert Uytterhoeven <geert@linux-m68k.org>
> orangecrab: Fix r0.1 user_led mapping

- litex_boards/platforms/tec0117.py
- litex_boards/targets/tec0117.py
This PR complements https://github.com/enjoy-digital/litex/pull/654 and adds support for the TEC0117 board.
Like the Icebreaker target, it puts the BIOS in flash, but since this board has internal bitstream flash and external user flash that is not accessible through JTAG, some hacky stuff is required to program the flash.
It currently uses 2kB sram, the minimal the bios was happy with. That's 2 bram primitives out of 26.
> Add initial support for Trenz TEC0117 board

- litex_boards/platforms/crosslink_nx_vip.py
- litex_boards/targets/crosslink_nx_vip.py
As is quite common for Lattice devkits, for some unknown reason the factory-shipped FTDI EEPROM config is broken. In order for the UART to work (and unlike other boards, there are no jumpers and the FTDI is wired for UART only), I needed to reset the config to a default state using ftdi_eeprom (less destructive approaches might also be available).
Not sure if anyone knows a better approach than this?
> Add CrossLink-NX VIP board platform and target

- litex_boards/platforms/ulx3s.py
The ULX3S board is also available with the 12F size of the ECP5.
> Add LFE5U-12F device for ULX3S

- litex_boards/platforms/qmtech_EP4CE15.py
- litex_boards/targets/qmtech_EP4CE15.py
> add Qmtech EP4CE15 coreboard support

- README.md
- litex_boards/platforms/litefury.py
- litex_boards/targets/litefury.py
- test/test_targets.py
LiteFury is an Artix-7 development board in the M.2 form factor for PCIe accelerator development. It's similar to the Aller but with an xc7a100t rather than an xc7a200t and no TPM module. 
product site: https://rhsresearch.com/collections/rhs-public/products/litefury
As far as testing goes, I've booted into the LiteX bios via a PCIe wishbone bridge with a crossover uart. mem_test passes and the console works.
Caveats: The PCIe data width is set at 64 bits because when set to 128 bits every computer I put the board in either fails to POST (custom i7-5820k system (UEFI)) or hangs when the OS tries to load (Dell Optiplex 980 w/ i7-860 (BIOS)). I don't know where to begin debugging this. I don't have any cables for the IO breakouts on this development board so I can't setup a UART at this …
> Support for the RHS Research LiteFury

- litex_boards/targets/mercury_xu5.py
This fixes https://github.com/litex-hub/litex-boards/issues/68.
> mercury_xu5: reduce cmd_latency to fix problems with DRAM leveling

- litex_boards/platforms/redpitaya.py
- litex_boards/targets/redpitaya.py
[redpitaya](https://www.redpitaya.com/) are zynq based boards with ADC and DAC.
This PR provides support for two variant:
- redpitaya/STEMlab 125-14: zynq xc7z010clg400 with 14 bits ADC & DAC @ 125MS/s
- redpitaya/SDRlab 122-16: zynq xc7z020clg400 with 16 bits ADC & 14 bits DAC @ 122MS/s
This PR allows to use the ARM cortex A9.
> add support for redpitaya14/16

- litex_boards/targets/orangecrab.py
Obviously --sdram-device takes the SDRAM device, not the ECP5 FPGA
device.
Fixes: bf3c9dc9bf97e3aa ("orangecrab: Add sdram selection option")
Signed-off-by: Geert Uytterhoeven <geert@linux-m68k.org>
> targets/orangecrab: Fix --sdram-device help text

- litex_boards/platforms/zybo_z7.py
This PR fixes an issue with the pin mapping of the Zybo Z7 board.
In fact, the external clock pin is tied to an incorrect pin, which was valid fro the Zybo board, but not for the Z7 version.
> zybo_z7: fix clock pin constraint

- litex_boards/targets/orangecrab.py
This PR fixes FPGA reset logic in `_CRG` to match one in `_CRGSDRAM`. Without this fix FPGA SRAM programming fails when SDRAM is not used.
The bug was introduced in https://github.com/litex-hub/litex-boards/commit/9b6ed6bdf1e2b16400db56900def800d8ef3ee78.
> Fix FPGA reset logic for orangecrab target

- litex_boards/platforms/nexys4ddr.py
- litex_boards/targets/nexys4ddr.py
This commit adds VGA support for the Nexys A7/ Nexys 4 DDR.
The VGA is however limited to RGB443 instead of the full 12bit RGB444.
This is because IO D8 which is MSB for Blue, is also used for ETH int_n.
This makes the final output have a yellow tint.
> nexys4ddr: add support for litexvideo VGA Terminal

- litex_boards/platforms/colorlight_5a_75b.py
With this changes I am able to synthesize a working liteX demo with vex-riscv, 8Mb SDRAM , UART on R7/T6 and ethernet on Phy0 on v8.0 PCB. I have copied J1 - J8 from [q3k/chubby75](https://github.com/q3k/chubby75/blob/master/5a-75b/hardware_V8.0.md) repo but did nor check all connectors.
> add colorlight v8.0 PCB

- litex_boards/platforms/logicbone.py
- litex_boards/platforms/orangecrab.py
When building linux-on-litex-vexriscv for OrangeCrab:
Warning: IOBUF 'spisdcard_clk' attribute 'SLEW' is not recognised (on line 207)
Warning: IOBUF 'spisdcard_mosi' attribute 'SLEW' is not recognised (on line 210)
Warning: IOBUF 'spisdcard_cs_n' attribute 'SLEW' is not recognised (on line 214)
Warning: IOBUF 'spisdcard_miso' attribute 'SLEW' is not recognised (on line 218)
Platforms using litex.build.lattice.LatticePlatform seem to support only
"SLEWRATE", not "SLEW".  Fix the few offenders in the LogicBone and
OrangeCrab platform definitions.
Signed-off-by: Geert Uytterhoeven <geert@linux-m68k.org>
> platforms/ecp5: Fix slewrate configuration

- litex_boards/platforms/genesys2.py
- litex_boards/targets/genesys2.py
Platform patch based on [this entry from the genesys2 board manual](https://reference.digilentinc.com/reference/programmable-logic/genesys-2/reference-manual#microsd_slot). Additionally, some minor cleanup modelled after the equivalent entries in the `nexys4ddr` platform file.
***EDIT***: added commit to support `--with-[spi-]sdcard` on the target build command line
> genesys2: LiteSDCard support

- litex_boards/targets/colorlight_5a_75x.py
Hi, I added an option to the colorlight board to customize the etherbone ip adress.
I also made the LED chaser optional on the colorlight board, because
the uart is enabled by default which uses the same pin as the LED.
> colorlight: Add option for etherbone ip address and LED chaser

- litex_boards/platforms/ecpix5.py
Missing pinout completion.
Now enable to detect SDCard presence on ECPIX5 board.
Details / diagnosis from Gabriel here:
https://github.com/litex-hub/linux-on-litex-vexriscv/issues/171
> Fix SDCard issue when no SDCard inserted in ECPIX5 board.

- litex_boards/platforms/ulx3s.py
- litex_boards/targets/ulx3s.py
A follow on from: https://github.com/litex-hub/litex-boards/issues/148. I wanted to be able to use the onboard flash of the ULX3S as a boot target. This PR adds a new `--with-spiflash` flag that will add the SPI master to the SoC, and lift it into the memory map.
The easiest way to define the `FLASH_BOOT_ADDRESS` [pre-processor definition](https://github.com/enjoy-digital/litex/blob/master/litex/soc/software/bios/boot.c#L468) in the bios was to just do an `soc.add_constant` call. I couldn't find any other board examples defining `FLASH_BOOT_ADDRESS`, so if there's a better way to do this (or a cleaner pattern), please let me know!
Because [this commit](https://github.com/enjoy-digital/litex/commit/41964f945cee71337e8e0998d597086b2ef94f77) removed SPI flashing functionality from the bios, …
> ULX3S: Make spiflash optionally accessible from the SoC, and bootable

- litex_boards/platforms/colorlight_i5.py
- litex_boards/targets/colorlight_i5.py
Hi,
This is a proposed colorlight i5 board support. Only one thing that is different from other boards would be that the ethernet transceiver on this board requires to configure with mdio before using the ethernet. targets/colorlight_i5.py writes it to the newly created include/generated/target.h with
```
os.makedirs(os.path.join(builder.software_dir, "include/generated"),
exist_ok=True)
write_to_file(
os.path.join(builder.software_dir, "include/generated", "target.h"),
"// Colorlight i5 needs this to disable TX data to clock delay.\n"
"#define TARGET_BIOS_INIT_FUNC() mdio_write(0, 0x1c, 0x8c00)")
```
and also defines a macro TARGET_BIOS_INIT
```
self.add_constant("TARGET_BIOS_INIT", 1)
```
when ethernet is enabled. I've added corresponding lines to litex software/bios/main.c which call …
> Add colorlight i5 board support

- litex_boards/platforms/netv2.py
- litex_boards/targets/netv2.py
This PR enables to choose the FPGA device of the netv2 board when executing the netv2 target script (similarly to the arty board target).
> netv2: add device variant to allow 100T as well

- litex_boards/platforms/ecpix5.py
> ECPIX-5: ddram: Add missing address pin.

- litex_boards/platforms/ztex213.py
- litex_boards/targets/ztex213.py
Support for the ZTEX USB-FGPA Module 2.13:
https://www.ztex.de/usb-fpga-2/usb-fpga-2.13.e.html
With (no-so-optional) expansion, either the ZTEX Debug board:
https://www.ztex.de/usb-fpga-2/debug.e.html
Or the SBusFPGA adapter board:
https://github.com/rdolbeau/SBusFPGA
> Support file for the ZTEX USB-FPGA Module 2.13

- litex_boards/platforms/arrow_sockit.py
- litex_boards/targets/arrow_sockit.py
Hi Florent,
I got a request from a user desperate for a serial connection
and I found this solution (include fix to programmer cable name).
Does lxterm work over jtag_atlantic?
(This I have not found out yet).
If not, what would I need to do to make it work?
Best regards,
Hans
> sockit: Fix cable name, default to jtag_atlantic

- litex_boards/targets/acorn_cle_215.py
- litex_boards/targets/arty.py
- litex_boards/targets/colorlight_5a_75x.py
- litex_boards/targets/colorlight_i5.py
- litex_boards/targets/fpc_iii.py
- litex_boards/targets/genesys2.py
- litex_boards/targets/kcu105.py
- litex_boards/targets/netv2.py
- litex_boards/targets/nexys4ddr.py
- litex_boards/targets/nexys_video.py
- litex_boards/targets/pano_logic_g2.py
- litex_boards/targets/qmtech_wukong.py
- litex_boards/targets/trellisboard.py
- litex_boards/targets/ulx3s.py
- litex_boards/targets/versa_ecp5.py
Collect `--with-ethernet`/`--with-etherbone`, `--with-spi-sdcard`/`--with-sdcard`, etc. into `ArgumentParser.add_mutually_exclusive_group()`s.  That way, we get pretty `--help` output, and appropriate error messages if somebody tries to ask for something that doesn't make sense.
> Be friendlier about incompatible options.

- litex_boards/targets/colorlight_i5.py
Hi,
I've mistakenly thought ecpdap can load a .svf stream file, though it ends up with
```
Error: ECP5 status register in incorrect state.
```
after the file transfer is done. This PR fixes it.
Regards,
kaz
> targets/colorlight_i5: use .bit stream instead of .svf when loading.

- litex_boards/platforms/arrow_sockit.py
- litex_boards/targets/arrow_sockit.py
Hi Florent,
I got the SDRAM module I have (the Winbond) now stable working error free:
litex> mem_test 0x40000000 0x2000000
Memtest at 0x40000000 (32MiB)...
Write: 0x40000000-0x42000000 32MiB    
Read: 0x40000000-0x42000000 32MiB    
Memtest OK
Interestingly the additional pin options made the memory errors worse,
so I left most of them out.
I am also now quite confident that I got the timing right.
In this version I won't need any additions to litedram,
because I create the timings in this module dynamically,
depending on the clock frequency, since the datasheet
specifies two timing values in clock cycles where litedram would expect it in nanoseconds.
> arrow_sockit: add support for MiSTer XS SDRAM modules

- litex_boards/platforms/vc707.py
The `create_clock -name sys_clk` entry was missing in the generated .xdc file, which leads to critical warnings in synthesis.
Adding this period constraint fixes it.
> vc707.py: clk156 add missing constraint

- litex_boards/platforms/arrow_sockit.py
- litex_boards/targets/arrow_sockit.py
jtag_atlantic is too slow to upload larger binaries.
We need a physical uart option.
> sockit: Add an option to plug in an UART via the GPIO daughter board, make connector pin numbers one-based

- litex_boards/platforms/vc707.py
according to:
https://www.xilinx.com/support/documentation/boards_and_kits/vc707/ug885_VC707_Eval_Bd.pdf
and confirmed on hardware.
> fix vc707 default_clk_period

- litex_boards/targets/arty.py
This is a companion PR to enjoy-digital/litex#822
This PR adds eth_ip_configurable switch to the arty.py target. The switch, used with the ethernet switch, allows to change local IP, remote IP and MAC address in runtime. It should not be used with the etherbone switch as it has no affect on the etherbone address.
> target/arty: add eth_ip_configurable switch

- README.md
- litex_boards/platforms/alveo_u280.py
- litex_boards/targets/alveo_u280.py
This PR is related to #156 with _target_ and _platform_ files for the Xilinx Alveo U280 accelerator card. Only the sysclk0/1, cpu_reset, LEDs, switches, serial port and DDR4 C0/C1 constraints are defined at this time.
> Alveo U280 board

- litex_boards/platforms/arrow_sockit.py
- litex_boards/targets/arrow_sockit.py
It's not perfect yet (the color timing of individual components seems to be off by one pixel,
but it is definitely useable.
> arrow_sockit: get video terminal working on VGA

- litex_boards/platforms/deca.py
This is a fix for #848 [https://github.com/enjoy-digital/litex/issues/848](https://github.com/enjoy-digital/litex/issues/848)
> fix #848: allow ram initialization in bitstream to enable block ram 

- litex_boards/platforms/qmtech_wukong.py
- litex_boards/targets/qmtech_wukong.py
fix ethernet clock (it's a GMII), add FB support over the HDMI connector (hdmi clock set from the resolution)
This and https://github.com/enjoy-digital/litex/pull/875 enable a working FB in Linux-on-Litex-Vexriscv.
This and forcing polling mode in Linux (see https://github.com/enjoy-digital/liteeth/issues/62 ) enable a working Ethernet in Linux-on-Litex-Vexriscv.
> Qmtech Wukong: updates

- litex_boards/targets/antmicro_lpddr4_test_board.py
We were using wrong RX delay which caused random errors as the PHY chip already introduces 1.2 ns delay.
> antmicro_lpddr4_test_board: fix ethernet rx delay issue

- litex_boards/targets/terasic_sockit.py
The video clock also needs to go away if the video terminal is not instantiated,
otherwise the project will have a build error.
> terasic_sockit: fix: make video clock also optional as video terminal is optional

- README.md
- litex_boards/targets/xilinx_alveo_u280.py
Following the previous pull request, where some of the changes were merged manually, this pull request corrects a few minor details such as:
- LED component is now on-demand similar to how PCIe is because my board crashes when one of the LEDs is turned on (evaluation silicon issue)
- frequency of 150MHz_1:4_600MHz in target and description file
- pass `cmd_latency      = 1` and `iodelay_clk_freq = 600e6` arguments to PHY
- am not 100% sure about the sdram setting `size          = 0x80000000`
I tested litex boot and several memory tests and identified a failing test that hopefully will help us understand what is wrong about the ddr4 controller.
[au280ddr4tests.txt](https://github.com/litex-hub/litex-boards/files/6401319/au280ddr4tests.txt)
> Minor fixes for AU280 [work in progress]

- litex_boards/platforms/lattice_ice40up5k_evn.py
- litex_boards/targets/lattice_ice40up5k_evn.py
Platform from migen, modified a little bit. Target inspired by FOMU (same FPGA but without USB).
Needs an external serial connection.
> Lattice iCE40 UltraPlus Breakout board (iCE40UP5K-B-EVN) added

- README.md
- litex_boards/platforms/qmtech_daughterboard.py
- litex_boards/platforms/qmtech_xc7a35t.py
- litex_boards/targets/qmtech_xc7a35t.py
- test/test_targets.py
I tested litex running on the core board. DDR memory works fine.
I tested the daughterboard (leds + buttons) with my nmigen-boards version of this
(see https://github.com/nmigen/nmigen-boards/pull/152)
Unfortunately my core board now is wired up to a custom project,
and it would be time consuming to tear it apart.
It builds with Vivado and I feel it is definitely worth sharing,
especially to avoid duplication of effort.
> add QMTECH XC7A35T core board + daughter board

- litex_boards/platforms/muselab_icesugar.py
I overlooked the FPGA connected USB port here
> icesugar: map the usb port

- README.md
- litex_boards/platforms/trenz_cyc1000.py
- litex_boards/targets/trenz_cyc1000.py
- test/test_targets.py
I prepared the initial support for the CYC1000 board by Trenz Electronic. Tested on HW, the generated design boots fine.
> CYC1000: Add initial support of CYC1000 board

- litex_boards/platforms/colorlight_5a_75b.py
As with the other versions, the clk pin can't be directly driven and has to be used with the usrmclk primitive. Tested, reading works
> Fix colorlight 5a 75b v6.1 flash pins

- setup.py
Otherwise setuptools finds an additional `test` package.
> setup.py: Exclude test package

- litex_boards/targets/digilent_basys3.py
Currently, the Litex design on the board only operates if you hold the reset button (BTNC) down.   This PR inverts the sense of the button, so that LiteX operates normally without the button pressed, and is reset when the button is pushed.   Tested on Basys3 rev C.
Signed-off-by: Tim Callahan <tcal@google.com>
> Basys3: Invert reset button, so that the board is reset when btnc is pushed.

- litex_boards/targets/colorlight_5a_75x.py
Leads to an increase in DP16KD usage, first noticed in https://github.com/enjoy-digital/liteeth/issues/70.
With full_mem_we:
```
Info: 	              DP16KD:    41/   56    73%
```
Without:
```
Info: 	              DP16KD:    29/   56    51%
```
Might also be relevant for other yosys/ecp5 targets.
Versions:
Yosys 0.9+4241 (git sha1 8733e1923, gcc 11.1.0 -march=native -mtune=generic -O2 -fno-plt -fPIC -Os)
nextpnr-ecp5 -- Next Generation Place and Route (Version ef1fbfc6)
Command:
```
python colorlight_5a_75x.py --build
```
> colorlight_5a_75x: Disable full_memory_we for l2 cache by default

- litex_boards/platforms/gsd_orangecrab.py
**Problems**
`SPIMaster` pad names are `clk`, `cs_n`, `mosi`, and `miso`.
However, `feather_spi` is using `sck` instead of `clk`, therefore
it is not able to use as-is for `SPIMaster`, for example,
with `add_spi` on Linux On LiteX VexRiscv.
**Solution**
In fact, `spisdcard` and other SPI related pad names are
using `clk`, only `feather_spi` is using `sck`.
Therefore, rename `sck` to `clk`.
> FIX: OrangeCrab Feather SPI pad name

- litex_boards/platforms/beaglewire.py
- litex_boards/targets/beaglewire_crossover.py
Added beaglewire platform and target file.
- Platform file for beaglewire can be found [here](https://github.com/litex-hub/litex-boards/blob/db9c98b28afcb64058662ff254f465cd63ff6a2a/litex_boards/platforms/beaglewire.py)
- Target file for beaglewire can be found [here](https://github.com/litex-hub/litex-boards/blob/db9c98b28afcb64058662ff254f465cd63ff6a2a/litex_boards/targets/beaglewire_crossover.py)
- Detailed guide for how to use the beaglewire litex can be found [here](https://beaglewire.github.io/Blogs/BeagleWire-Litex.html)
Demo of working litex on beaglewire with uart wb crossover: https://www.youtube.com/watch?v=mx4KWYq29I0
kindly review it and let me know if any changes are required. 
regards,
omkar bhilare
ombhilare999@gmail.com
> beaglewire platform and target added

- litex_boards/platforms/lattice_crosslink_nx_evn.py
- litex_boards/targets/lattice_crosslink_nx_evn.py
This board is documented as having the LIFCL-40-9BG400C part, but some
versions of the board exist which were fitted with LIFCL-40-8BG400CES,
an engineering sample part. The distinction is important because the
engineering sample requires a different device ID to be embedded in the
bitstream. If you try to build a bitstream for LIFCL-40-9BG400C and load
it onto LIFCL-40-8BG400CES the configuration fails (indicated by the red
"INITN" LED on this board).
Accept --device to allow the user to specify which FPGA part their board
has.
> lattice_crosslink_nx_evn: allow specifying the FPGA device

- litex_boards/targets/lattice_crosslink_nx_evn.py
Setting MASTER_SPI_PORT=SERIAL causes the SPI flash pins to be reserved
for use by the sysCONFIG logic, and prevents user logic from assigning
them. This made it impossible to have a Litex design which accesses the
SPI flash on this board.
Remove the setting, so that we get the default behaviour which permits
user logic to assign these pins. In the unlikely event that someone
needs the pins to stay reserved for sysCONFIG after configuration (I'm
not sure why this would be needed) they could explicitly add this
command in their design.
> lattice_crosslink_nx_evn: don't set MASTER_SPI_PORT=SERIAL

- litex_boards/platforms/alchitry_au.py
- litex_boards/targets/alchitry_au.py
Add the Au board from Alchitry to LiteX.
System frequency is 83.333333 MHz, as the -1 speed grade xc7a35t can only manage 667 MHz DDR3L RAM.
Gated by https://github.com/enjoy-digital/litedram/pull/274 (timings for the RAM module on the board)
```
./alchitry_au.py --build --with-spi-flash --load
```
> Add Alchitry Au as new board

- litex_boards/platforms/alchitry_mojo.py
- litex_boards/targets/alchitry_mojo.py
Add a board description for the (Alchitry / Embedded Micro) Mojo V3. Was able to get HDMI video out with the HDMI shield and some careful management of cache and SRAM sizes (the XC6SLX9 is sorely lacking in SLICEMs, which the FIFOs in litevideo really seem to want).
> Add Mojo V3 support

- litex_boards/platforms/rz_easyfpga.py
- litex_boards/targets/rz_easyfpga.py
Thanks @enjoy-digital for the pointer! You were right, the SDRAM clk phase did need to be adjusted. Adding wires had somehow mitigated this.
Reference: #270
> rz_easyfpga: adjust SDRAM clk phase, also add 1:2 rate

- README.md
- litex_boards/platforms/qmtech_wukong.py
- litex_boards/targets/qmtech_wukong.py
This adds support for v2 of the board via a --board-version argument
and a way to select the FPGA speed grade via a --speed-grade argument.
Note that the speed grade now defaults to -1. QMTech confirmed that
V1 of the board were made in two batches, one with -1 and one with -2,
while V2 of the board is all -1. So -1 is the safer default.
This also fixes the inversion of j10 and j11 and a typo in the pin
definition of jp3
Signed-off-by: Benjamin Herrenschmidt <benh@kernel.crashing.org>
> Wukong board improvements

- README.md
- litex_boards/platforms/rz_easyfpga.py
- litex_boards/targets/rz_easyfpga.py
- update README
- delete some unnecessary toolchain commands (copied from trenz boards)
- use minimal cpu_variant by default when vexriscv is selected
> rz_easyfpga: cleanup and ease of use

- litex_boards/targets/efinix_trion_t20_bga256_dev_kit.py
This works as is, but bitstream block board if parameters are not configured right as proposed by https://github.com/enjoy-digital/litex/pull/1068
> Enable writing to flash for T20

- litex_boards/platforms/terasic_de2_115.py
Signed-off-by: lapd <lapd@soc.one>
The DE2-115 kit has built-in RS322 port. It's better to use that port than using extension slot
> Use built-int RS232 port

- litex_boards/platforms/qmtech_daughterboard.py
- litex_boards/targets/qmtech_xc7a35t.py
Hi Florent, here two fixes:
UART lines were swapped (for all boards that use the daughterboard).
Also removed a redundant statement for the XC7A35T board.
> QMTech boards: fix swapped RX/TX lines, remove double uart replacer

- litex_boards/platforms/qmtech_5cefa2.py
- litex_boards/targets/qmtech_5cefa2.py
A new board arrived!
```
(c) Copyright 2012-2021 Enjoy-Digital
BIOS built on Nov  5 2021 09:48:15
BIOS CRC passed (cfd8447f)
Migen git sha1: 7507a2b
LiteX git sha1: 9ecb1e61
CPU:		VexRiscv @ 75MHz
ROM:		128KiB
SRAM:		8KiB
L2:		8KiB
SDRAM:		32768KiB 16-bit @ 75MT/s (CL-2 CWL-2)
Read: 0x40000000-0x40200000 2.0MiB     
Memtest OK
Memspeed …
```
> Add support for QMTech 5CEFA2 board (Cyclone V)

- litex_boards/targets/qmtech_10cl006.py
This adds the missing spi flash command line option to the 10cl006 board
> 10cl006: add missing spiflash option

- litex_boards/platforms/qmtech_10cl006.py
- litex_boards/platforms/qmtech_5cefa2.py
- litex_boards/platforms/qmtech_daughterboard.py
- litex_boards/platforms/qmtech_ep4ce15.py
- litex_boards/targets/qmtech_10cl006.py
- litex_boards/targets/qmtech_5cefa2.py
- litex_boards/targets/qmtech_ep4ce15.py
Finally! Got it running at 105MHz!
Spent half a day on this:
Also the serial needed another fix to be able to switch correctly from core board to daughterboard.
This possibly depends on my pull request in LiteDRAM.
```
(c) Copyright 2012-2021 Enjoy-Digital
BIOS built on Nov  6 2021 09:39:32
BIOS CRC passed (fff2de9e)
Migen git sha1: 7507a2b
LiteX git sha1: 9ecb1e61
CPU:		VexRiscv @ 105MHz
ROM:		128KiB
SRAM:		8KiB
L2:		8KiB
SDRAM:		32768KiB 16-bit @ 105MT/s (CL-3 CWL-3)
Switching SDRAM to software …
```
> QMTech Altera fixes

- litex_boards/platforms/sqrl_acorn.py
OpenOCD still struggles to program Artix flash when it's not the only device in a JTAG chain - but Vivado handles this easily, so I find the option useful.
CFGBVS and CONFIG_VOLTAGE should be correctly set in all designs according to Vivado.
> sqrl_acorn: add vivado programmer option, fix warnings

- litex_boards/targets/terasic_sockit.py
Now that the timings of the winbond chip has been verified working as expected,
we can use it here too.
> terasic_sockit now also can use the DRAM module from litedram

- litex_boards/platforms/qmtech_10cl006.py
- litex_boards/targets/qmtech_10cl006.py
This pin was wrong.
Now that the c library builds I could test the target.
Unfortunately I could not find a configuration which would fit the device.
Even SERV with 0x1000 sram would not fit (by a bit).
Since there is no hierarchial design I have no idea where to save some gates/mem.
So I disabled the CPU and just added an uartbone to be able to interact with the remaining components.
> Wrong pin / use default setup without CPU

- litex_boards/targets/sipeed_tang_nano.py
- litex_boards/targets/sipeed_tang_nano_4k.py
sipeed_tang_nano_4k.py did not compile for me because standard VexRiscv required too many BSRAMs (15 vs 10 available):
```
ERROR (RP0002) : The number(15) of BSRAM in the design exceeds the resource limit(10) of current device. And RAM_STYLE maybe the useful user assignment to change the inference result
```
And minimal VexRiscv at least compiles.
Besides changes made to sipeed_tang_nano.py sipeed_tang_nano_4k.py to match https://github.com/enjoy-digital/litex/pull/1115 .
> Fix Sipeed Tang Nano 4k example compilation; adapt Gowin PLL class changes

- litex_boards/platforms/terasic_de1soc.py
- litex_boards/targets/terasic_de1soc.py
The platform description for DE1-SoC was missing useful pin descriptions, including user LEDs, keys, switches, VGA output and GPIO ports. Also bitstream programming via `--load` did not work because of missing settings for `quartus_pgm`. This pull request fixes the issues described above.
> Better support for DE1-SoC

- litex_boards/targets/sipeed_tang_nano_4k.py
Add options to build with Gowin ARM hard CPU (--cpu-type=gowin_emcu). 
Software is not ready for ARM, so by default stays with vexriscv as before.
I changed options a bit so that vexriscv now requires --cpu-variant=minimal on command line - so that vexriscv is not hardcoded anymore, any CPU can be chosen from the command line.
> sipeed_tang_nano_4k: add option to build with Gowin EMCU

- litex_boards/targets/efinix_titanium_ti60_f225_dev_kit.py
Tested and works well:
```
Initializing W25Q64JW SPI Flash @0x00800000...
Enabling Quad mode...
SPI Flash clk configured to 25 MHz
Memspeed at 0x800000 (Sequential, 4.0KiB)...
Read speed: 2.3MiB/s
Memspeed at 0x800000 (Random, 4.0KiB)...
Read speed: 1.3MiB/s
```
> Titanium spi

- litex_boards/targets/tinyfpga_bx.py
I was unable to run BIOS until I fixed `bios-flash-offset` to `0x50000.`
Not sure where the original value 0x60000 comes from, but tinyprog on my kit shows that `userdata` area is at `0x50000`.
Could it be that there are different BX variants?
```
$litex tinyprog -m
[
{
"boardmeta": {
"name": "TinyFPGA BX",
"fpga": "ice40lp8k-cm81",
"hver": "1.0.0",
"uuid": "8503d354-fcf6-4c92-9e16-016e3e7f229a"
},
"bootmeta": {
"bootloader": "TinyFPGA USB Bootloader",
"bver": "1.0.1",
"update": "https://tinyfpga.com/update/tinyfpga-bx",
"addrmap": {
"bootloader": "0x000a0-0x28000",
"userimage": "0x28000-0x50000",
"userdata": "0x50000-0x100000"
}
},
"port": "/dev/ttyACM0"
}
]
```
Also tried to pass argument `--bios-flash-offset=0x50000` but even when I set it hexadecimal or decimal number, I always get …
> Fix bios-flash-offset for tinyFPGA

- litex_boards/targets/muselab_icesugar_pro.py
The change is to use the same convention as in other boards: SPI Flash disabled by default, enabled by option.
> Option --with-spi-flash for iCESugar-Pro

- litex_boards/platforms/trenz_tec0117.py
Seems like openFPGALoader capitalized letter 'B' in the past or made the boards case sensitive. Now flash works properly.
> Fix cannot find board 'littlebee'

- litex_boards/platforms/snickerdoodle.py
- litex_boards/targets/snickerdoodle.py
Basic files for Snickerdoodle support. The target file downloads a basic XCI file by default. This can be overridden using the **--xci-file** option. I also added a **--target** option to specify the programmer hardware target.  I am not sure what would need to be done to support the XC7Z020 used in the Snickerdoodle Black.
> Initial release for Snickerdoodle

- litex_boards/platforms/digilent_zedboard.py
- litex_boards/targets/digilent_zedboard.py
Uses "ZedBoard" Zynq IP preset built into Vivado for PS7 configuration (can be easily extended with Tcl if necessary).
Relies on https://github.com/enjoy-digital/litex/pull/1141 .
Required Xilinx C libraries (https://github.com/Xilinx/embeddedsw) are cloned into build directory during build.
Both SRAM and ROM regions are currently in actual DRAM address space - this is just a simplification for tests.
BIOS can be executed on Zynq using XIlinx xsct and JTAG with such a script: https://github.com/sergachev/litex-template/blob/dev/scripts/ps7_boot.tcl
> LiteX BIOS on Zedboard

- litex_boards/platforms/trenz_c10lprefkit.py
The trenz Cyclone 10 lp RefKit (c10lprefkit) has an integrated arrow usb blaster, which needs to be added to quartus before usage (as described [here](https://wiki.trenz-electronic.de/display/PD/Arrow+USB+Programmer)). This patch uses that programmer for loading the bitstream.
Before:
```console
> ./trenz_c10lprefkit.py --load
[...]
Error (213013): Programming hardware cable not detected
Traceback (most recent call last):
File "./trenz_c10lprefkit.py", line 125, in <module>
main()
File "./trenz_c10lprefkit.py", line 122, in main
prog.load_bitstream(os.path.join(builder.gateware_dir, soc.build_name + ".sof"))
File "/home/wilbrandt/litex/litex/litex/build/altera/programmer.py", line 19, in load_bitstream
self.call(["quartus_pgm",
File …
```
> Use Arrow-USB-Blaster for trenz c10lprefkit

- litex_boards/targets/digilent_cmod_a7.py
This allows to also synthesize with 100 MHz instead of 48. Not sure, why these clocks are in. Possible copy and paste leftovers?
The cmod a7 does not have any DRAM, and no immediate need for serdes.
If these clock domains are some sort of litex convention, then please close.
> digilent_cmod_a7: Remove unused clocks.

- litex_boards/targets/digilent_zedboard.py
This cleans up Zynq memory map and removes a hack that is not necessary anymore.
> Fix Zedboard software

- litex_boards/platforms/xilinx_zcu106.py
- litex_boards/targets/xilinx_zcu106.py
1. Add ZCU106 PL DDR4 PHY IOs. Then we can upload firmware to board for CFU playground framework.
2. According to the schematic diagram, it can be confirmed that the rst pin is active at high level.
DDR, reset pin and CFU tested pass.
> xilinx_zcu106: add DDR4 interface and fix reset error

- litex_boards/platforms/sipeed_tang_nano_9k.py
- litex_boards/targets/sipeed_tang_nano_9k.py
Add a new board based on GW1N(R), which is Sipeed Tang Nano 9K.
The PSRAM built in cannot be utilized yet, and all display output isn't tested by me now due to lack of hardware.
> sipeed_tang_nano_9k: new board

- litex_boards/platforms/digilent_cmod_a7.py
- litex_boards/targets/digilent_cmod_a7.py
Add both "--flash" and "--with-spi-flash"; tested on board.
4MB flash mapped at 0x00400000.
Signed-off-by: Tim Callahan <tcal@google.com>
> Digilent CMOD A7: add flash support.

- litex_boards/platforms/digilent_arty.py
- litex_boards/targets/digilent_arty.py
This pull request requires the related one: https://github.com/enjoy-digital/litex/pull/1180
Example command for testing (NOTE: some parameters are *required* to make it work as the clock frequency and memory setting):
`./digilent_arty.py --sys-clk-freq=50e6 --integrated-main-ram-size=8192 --cpu-type=femtorv --toolchain=yosys+nextpnr --build`
PATH needs to point to `/prjxray/utils/` to find required scripts
the "Misc()" attributes seems not to affect only the previously defined signals so it's not accepted in yosys+nextpnr toolchain
> Add tweaks to Arty board to support yosys+nextpnr toolchain

- litex_boards/__init__.py
- litex_boards/platforms/alinx_axu2cga.py
- litex_boards/targets/alinx_axu2gca.py
[alinx AXU2GA](http://www.alinx.com/en/index.php/default/content/101.html) is a board based on XCZU2CG (Zynq Ultrascale+ MPSoC)
Signed-off-by: Gwenhael Goavec-Merou <gwenhael.goavec-merou@trabucayre.com>
> alinx_axu2gca: new board

- litex_boards/platforms/digilent_arty_z7.py
- litex_boards/targets/digilent_arty_z7.py
Tested with arty Z7 10 (xc7z010) & arty Z7 20 (xc7z020).
zynq7000 variant not supported due to xilinx's specifics commands required to generates the CPU macro template.
> digilent arty z7: allows toolchain selection (PL only)

- litex_boards/targets/gsd_orangecrab.py
The 85F orangecrab board exists, and works fine when this option is set to 85F, but leaving it out of the help is a bit confusing.
> Add 85F to help for orangecrab device

- litex_boards/platforms/xilinx_kv260.py
- litex_boards/targets/xilinx_kv260.py
The configuration is sufficient to run LiteX BIOS on Cortex-A53 core #0.
Can be executed on hardware using JTAG with a following [xsct script](https://github.com/sergachev/litex-template/blob/kv260/scripts/psu_boot.tcl); `make -f Makefile.kv260 load` in https://github.com/sergachev/litex-template/tree/kv260 will build everything and run `xsct` in the end.
Relies on https://github.com/lucaceresoli/zynqmp-pmufw-builder to create a generic PMU firmware; first build will take a while because it includes a cross-toolchain.
> Add Xilinx KV260 support

- litex_boards/platforms/terasic_de1soc.py
Fixes quartus build error:
```
Error (171016): Can't place node "seven_seg5[6]" -- illegal location assignment PIN_AA2 File: /home/arusekk/src/fpga-proj/build/de1soc/gateware/de1soc.v Line: 49
```
> Fix seven_seg pin assignment typo in DE1-SoC

- .gitignore
- README.md
- litex_boards/targets/terasic_de0nano.py
- litex_boards/targets/xilinx_alveo_u280.py
Summary of changes:
- added `targets/ip/` to .gitignore
- updated the README.md description for Alveo board
- added line that links the HBM channel 0 to be used as main RAM
I tested this alone (targets ./xilinx_alveo_u280.py) and the bitstream is generated, boots into LiteX BIOS, and will create the linux-litex-vexriscv PR next.
> Alveo U280 with HBM now working for Linux

- litex_boards/platforms/rcs_arctic_tern_bmc_card.py
- litex_boards/targets/rcs_arctic_tern_bmc_card.py
Add initial (pre-release) support for the upcoming Arctic Tern ECP5-based modules and their associated BMC development carrier card.
> Add initial support for RCS Arctic Tern boards

- litex_boards/platforms/colorlight_i5.py
- litex_boards/targets/colorlight_i5.py
The ColorLight i9 v7.2 is very similar to the i5 v7.0.
It has an ECP5 -45F instead of the -25F. The user LED is on a different pin. It has a different SPI Flash part.
I've modified the colorlight_i5.py files to take a board="i9" parameter :+1: 
--board i9 --revision 7.2
See https://github.com/wuxx/Colorlight-FPGA-Projects/blob/master/colorlight_i9_v7.2.md for the hardware description.
> Add ColorLight i9 v7.2

- litex_boards/platforms/antmicro_datacenter_ddr4_test_board.py
- litex_boards/targets/antmicro_datacenter_ddr4_test_board.py
This PR fixes the antmicro datacenter board definition:
- adjusted pins corresponding to the RDIMM datacenter board
- increased clk frequency to 100 MHz to reach 800 MT/s
- use A7DDRPHY (without odelays)
- add i2c
> antmicro datacenter: fix pins and increase freq

- litex_boards/platforms/antmicro_datacenter_ddr4_test_board.py
This fixes a typo in https://github.com/litex-hub/litex-boards/pull/359 for which the i2c pads were inverted
> antmicro_datacenter: fix i2c pads assignment

- litex_boards/platforms/adi_adrv2crr_fmc.py
- litex_boards/targets/adi_adrv2crr_fmc.py
This is a carrier board with a SoM mounted on it.
There is also an FMC connector that can accept another
AD-FMCOMMS8-EBZ to get two more ADRV9009 RFIC but support for
that is not added yet.
Note that the PCIe support requires :
- Change the .xci in the litepcie to use the right Quad
- Revert litex 3c34039b731b42e27e2ee6c8e399e5eb8f3a058f so the
timing constrainst of litepcie apply correctly
Signed-off-by: Sylvain Munaut <tnt@246tNt.com>
> adi_adrv2crr: Add support for the ADI ADRV2CRR with ADRV9009-ZU11EG SoM

- litex_boards/platforms/sipeed_tang_nano_9k.py
- litex_boards/targets/sipeed_tang_nano_9k.py
1. update only target for sipeed_tang_nano_9k platform and target
2. update LiteX to support PowerShell and WSL host for tang_nano_9k
3. add gowin programmer support, but with limitations:
- there is no details info for external spi programming with programmer_cli, so it's support not working by now.
- Verify got stuck, so it's also disabled by default.
- programming interface is compatible with openFPGALoader
4. test with oss-cad-sute (from yosysHQ) under Powershell and also WSL(ubuntu 20.04)
> add Gowin programmer support

- litex_boards/platforms/antmicro_lpddr4_test_board.py
Currently if you use user button 1 in a design, Vivado will prompt a critical warning:
```
CRITICAL WARNING: [Common 17-69] Command failed: 'B9' is not a valid site or package pin name. [/build/antmicro_lpddr4_test_board/gateware/antmicro_lpddr4_test_board.xdc:211] 
```
This happens because there is an issue with pin name which I believe is a typo. Pin `B9` is a pin assigned to GND in `xc7k70tfbg484` part. When you look at LPDDR4 `.kicad_pcb` file you can see that this user button should be connected to `B8` pin:
```
(pad B8 smd circle (at -3.5 -9.5 270) (size 0.51 0.51) (layers F.Cu F.Paste F.Mask)
(net 456 USR_BTN2))
```
This resolves an issue with critical warning.
> lpddr4_test_board: Fix button pin

- litex_boards/platforms/adi_adrv2crr_fmc.py
Even though the schematic and bom call for speedgrade 1, this was only for
the prototypes.
All productions units have been updated to speedgrade 2.
See this thread:
https://ez.analog.com/fpga/f/q-a/112356/adrv9009-zu11eg-speed-grade
And the official HDL project for the board:
https://github.com/analogdevicesinc/hdl/blob/master/projects/adrv9009zu11eg/adrv2crr_fmc/system_project.tcl#L16
Signed-off-by: Sylvain Munaut <tnt@246tNt.com>
> adi_adrv2crr: Upgrade part to speedgrade 2

- litex_boards/platforms/antmicro_datacenter_ddr4_test_board.py
- litex_boards/targets/antmicro_datacenter_ddr4_test_board.py
This PR adds all the missing peripherals to the DDR4 datacenter platform:
- HDMI
- SPI Flash
- HyperRam (fixed)
> DDR4 datacenter: add missing peripherals

- litex_boards/platforms/efinix_t8f81_dev_kit.py
- litex_boards/targets/efinix_t8f81_dev_kit.py
Requires https://github.com/enjoy-digital/litex/pull/1254 to load or flash
Built with
```
python ./litex_boards/targets/efinix_t8f81_dev_kit.py --no-uart --build --load
```
> [enh] added efinix t8f81 dev kit

- litex_boards/targets/gsd_butterstick.py
The Microchip KSZ9031RNX PHY on the Butterstick has a default 1.2ns
internal RX delay so we shouldn't add the default 2ns MAC delay.
In testing with Linux on vexriscv I haven't seen any difference either
way, but with liteeth in Microwatt I have seen 30%+ packet loss when
receiving from certain ethernet devices (RTL8153 and AX88179 usb-gige
adapters, a GS105 switch didn't show the problem). Setting RX delay=0
resolves the problem. A TX delay is still required by the PHY.
Adding @gregdavill for any thoughts.
> butterstick: set ethernet rx_delay to 0ns

- litex_boards/targets/digilent_basys3.py
Delete an additional "o" in "builder" object. It makes not possible to program the Basys 3 out-of-the-box.
> Delete additional "o" in "builder" object

- litex_boards/platforms/enclustra_mercury_kx2.py
Since start this board has a very strange issue:
As long as the DDR RAM is activated, the board goes completely dead
(LED chaser not working, all LEDs dark, no output on serial.)
In this pull request I already added all the properties from the Enclustra reference
design.
But nevertheless, the issue persists.
I use Vivado 2020.2.
Do you have any idea why the presence of the DDR PHY causes the whole design to go dead?
> enclustra_mercury_kx2: add clk100, leds, base board serial, DDR3 termination

- litex_boards/platforms/muselab_icesugar_pro.py
- litex_boards/targets/muselab_icesugar_pro.py
- use P4 header for a waveshare ethernet phy module
- add --with-ethernet, --with-etherbone, --eth-ip, and --eth-dynamic-ip
target configuration options
> muselab icesugar pro: add ethernet/etherbone support

- litex_boards/targets/icebreaker.py
- litex_boards/targets/icebreaker_bitsy.py
- litex_boards/targets/kosagi_fomu.py
- litex_boards/targets/lattice_ecp5_evn.py
- litex_boards/targets/lattice_ecp5_vip.py
- litex_boards/targets/lattice_ice40up5k_evn.py
- litex_boards/targets/muselab_icesugar.py
- litex_boards/targets/qwertyembedded_beaglewire.py
- litex_boards/targets/rcs_arctic_tern_bmc_card.py
- litex_boards/targets/tinyfpga_bx.py
`LatticeIcestormToolchain` and `LatticeTrellisToolchain` provides addiitonal CLI arguments to modify/adapts `NextPnr behaviour. But at the target level these are never used.
This patch add required import, appends `args` with them and pass results to builder.builder method
> honours lattice toolchain args

- litex_boards/targets/digilent_basys3.py
This removes a redundancy that prevents a target to build with `--with-sdcard` and `--with-spi-sdcard` parameters.
> target: basys3: Remove redundant sdcard additions

- litex_boards/platforms/antmicro_datacenter_ddr4_test_board.py
Data Masks (DM) are unsupported on x4 devices and wrong pins were assigned.
> Remove DM signals assignment from DDR4 Datacenter platform

- litex_boards/platforms/sipeed_tang_nano_4k.py
According to Issue #411, I have added Tang Nano 4k support for GoWin Educational IDE v1.9.8.03
> Added Tang Nano 4k Support for GoWin Educational IDE v1.9.8.03

- litex_boards/targets/digilent_arty.py
Enables interrupt requests for the exposed GPIOs if the SoC is capable of handling interrupts.
> digilent_arty: make GPIOs interrupt-capable if SoC has IRQs enabled

- litex_boards/platforms/sipeed_tang_primer_20k.py
- litex_boards/targets/sipeed_tang_primer_20k.py
@sipeed provides two docks for tang primer 20k core board: one called simply **dock** (expected for october) and **lite** version with:
- 2 buttons
- 2 switches
- 4 PMODs
- 2 2 x 20 headers
This PR adds the definition for *io* and *connectors* and an argument to select between docks version. Default dock is left unchanged, user has to explicitly set `--dock lite`.
It also move serial node at core level: **lite** has no onboard serial adapter (*rx* and *tx* are available only on core board **J1** connector), it disable inconditionnaly **led_chaser** because there is no leds at all.
Also toolchain is explicitly set at target level and it fix *CARD1* typos.
> sipeed_tang_primer_20k: adding dock lite support

- litex_boards/platforms/radiona_ulx3s.py
Tested on LFE5U-85F:
```
from litex.build.generic_platform import *
from litex_boards.platforms import radiona_ulx3s
import design
platform = radiona_ulx3s.Platform(device="LFE5U-85F")
in1 = platform.request("user_button", 1)
in2 = platform.request("user_button", 2)
sum_led1 = platform.request("user_led")
sum_led2 = platform.request("user_led", 1)
status_led = platform.request("user_led", 3)
module = design.adder()
module.comb += module.in1.eq(in1)
module.comb += module.in2.eq(in2)
module.comb += sum_led1.eq(module.sum[0])
module.comb += sum_led2.eq(module.sum[1])
module.comb += status_led.eq(1)
platform.build(module)
prog = platform.create_programmer()
prog.load_bitstream("build/top.bit")
```
> radiona_ulx3s: add buttons

- litex_boards/targets/sipeed_tang_primer_20k.py
`CLKDIV` primitive must have `RESETN` and `CALIB` set to an explicit value. Without that nothing is produce on output.
By fixing that issue HDMI is now working.
Tested with **lite** dock, a @machdyne [DDMI PMOD](https://machdyne.com/product/ddmi-pmod/) and with colorbars and terminal.
> targets/sipeed_tang_primer_20k: fix CLKDIV (disable reset and calibration)

- litex_boards/platforms/sipeed_tang_primer_20k.py
- litex_boards/targets/sipeed_tang_nano_4k.py
- litex_boards/targets/sipeed_tang_nano_9k.py
- First commit: update sipeed tang Nano 4k to replace the generic `VideoHDMIPHY` by `VideoGowinHDMIPHY`. This commit, also, adds `with-video-terminal` argument.
- Second: update sipeed tang Primer 20k platform to use new `add_connector`. The use of `VideoGowinHDMIPHY` is posponed until behaviour is checked with dock standard
- last: replace the generic `VideoHDMIPHY` by `VideoGowinHDMIPHY`
> Update sipeed tang boards

- litex_boards/platforms/gsd_butterstick.py
- litex_boards/targets/gsd_butterstick.py
I ran into an issue while trying to get LiteX running on my Butterstick, it was pointed out to me that the example expects a JTAG adapter for programming the board, rather than the onboard USB. I added the option to select between "jtag" and "dfu" while programming so that the board can be programmed without an additional adapter. If no programmer option is specified, it defaults to a JTAG programmer, to maintain compatibility with existing code.
> Adding DFU Support to the Butterstick Platform

- litex_boards/platforms/lattice_crosslink_nx_evn.py
- litex_boards/targets/lattice_crosslink_nx_evn.py
e.g. the following was tested:
```
python3 lattice_crosslink_nx_evn.py --build --toolchain oxide --programmer ecpprog --load
```
with output:
```
Info: Program finished normally.
init..
reset..
programming..
Bye.
IDCODE: 0x110f1043 (LIFCL-40)
NX Status Register: 0x0000150100400100
NX Status Register: 0x0000150100400e50
NX Status Register: 0x0000150100400100
```
> add option to use ecpprog for crosslink-nx eval board

- litex_boards/targets/litex_acorn_baseboard.py
With this [PR](https://github.com/enjoy-digital/litex/pull/1442) focused on fixing this [issue](https://github.com/enjoy-digital/litex/issues/1439) blue and red colors are swapped. This fix as for consequence the need to update all targets where `pn_swap` is used.
Currently two targets uses this option `sipeed_tang_primer_20k` and `litex_acorn_baseboard`. Former has no needs to be updated since all channels must be swapper but latter has only channels 1 and 2 to permut -> this PR fix that by replacing **b** by **r** (aka channel 2).
> targets/litex_acorn_baseboard: fix pn_swap

- litex_boards/platforms/mnt_rkx7.py
- litex_boards/targets/mnt_rkx7.py
This is an update for the MNT RKX7 files to make it compatible with the release version (tested in MNT Reform motherboard/carrier). Details: https://source.mnt.re/reform/reform-kintex-som
Hardware Changes from D-1:
- The DDR3 memory routing was completely redone for a less congested layout and avoiding crosstalk. This fixed some address bus errors of the first version.
- The TC358778XBG MIPI encoder was removed. Instead, 24-bit parallel RGB, clocks and extra GPIOs are routed out to a new 50 pin FPC header. This makes the module more flexibly usable.
- We designed a new adapter PCB featuring the Analogix ANX9807 RGB to eDP chip. We are able to successfully drive MNT Reform's eDP Full HD display.
- The TUSB1310ZAY USB3/2 PHY was removed as it is EOL, expensive and there was is no available …
> MNT RKX7: update platform and target for D-2 release

- litex_boards/targets/digilent_arty_z7.py
As mentionned in issue #434 arty_z7 board fails to build when `--cpu-type zynq7000` is selected due a missing reset address.
This PR fix this issue by adding flash region.
> targets/digilent_arty_z7: add flash region

- litex_boards/platforms/isx_im1283.py
- litex_boards/targets/isx_im1283.py
ISX iM1283 is a "simple eDP signal generator" which utilizes a XC7A100T FPGA, and come with a header populated with the FPGA's JTAG.
This commit adds initial reverse engineered IOs including the DDR3 DRAM (which cannot work reliably @ DDR3-800, so the system clock is defaultly set to 80MHz now), two LEDs and SD slot.
Signed-off-by: Icenowy Zheng <uwu@icenowy.me>
> Add ISX iM1283 board

- litex_boards/targets/redpitaya.py
redpitaya board fails to build when --cpu-type is set to **zynq7000**. This is
due to a missing reset address and `csr` region.
This PR fix this issue by adding the **flash** and **csr** region.
It also disable the uart and set `integrated_ram_size` to 0.
> targets/redpitaya: fix csr & reset region

- litex_boards/platforms/fpgawars_alhambra2.py
- litex_boards/targets/fpgawars_alhambra2.py
This PR adds the open source board FPGAWars Alhambra II.
It uses SPI Flash to store the BIOS/Code due to the lack of LEs to store as ROM.
> Add FPGAWars Alhambra II

- litex_boards/platforms/digilent_nexys4.py
- litex_boards/platforms/digilent_nexys4ddr.py
Symbiflow/f4pga don't recognize the part name xc7a100t-CSG324-1, so change it to xc7a100tcsg324-1 which works with both f4pga and Vivado.
> platforms/nexys4*: Update part name

- litex_boards/platforms/alinx_axu2cga.py
`alinx_axu2cga` build fails with:
```
AttributeError: 'Platform' object has no attribute 'psu_config'
```
This attribute has been added by commit 50654f1b7b43249c90dbd87d9a2ce66f7adeb949 at same time as `psu_config` but seems be lost lost at merge time (maybe a conflict with the commit b53b79821e757a92ed9b7f15d7ebe5ad7a0bbd44)
This PR re-add this attribute to fix build.
> platforms/alinx_axu2cga: adding missing psu_config at platform level

- litex_boards/platforms/digilent_zybo_z7.py
- litex_boards/targets/xilinx_zybo_z7.py
(This pull-request is the second attempt of  https://github.com/litex-hub/litex-boards/pull/423)
As mentioned in the old pull-request the Zynq7000 could not be build on the Zybo-Z7-20.  To fix this I added two variants for the Zybo platform digilent_zybo_z7.py, so that the correct fpga device is selected. 
Furthermore I added a config for the ps7. As I don't have a zybo-z7-10, I only made a config for the z7-20 and the target is still using the downloaded .xci file for z7-10. 
For the target I fixed the Zynq7000 integration by introducing Memory Regions and a finalize-function like its done for the arty-z7. 
Additionally I added the "--with-ps7" option, which initializes the processing_system of the zybo board and connects it to a soft CPU via the S_GP0 AXI bus, so that all the Modules …
> Zybo: Fix for Zynq7000 and use ps7 as submodule for Soft-CPUs

- litex_boards/targets/icebreaker_bitsy.py
Tested on v1.1b board with `./icebreaker_bitsy.py --build --cpu-variant=minimal --flash`
Signed-off-by: Tim Callahan <tcal@google.com>
> Add LedChaser to iCEBreaker-bitsy.

- litex_boards/platforms/sipeed_tang_primer_20k.py
Correct SODIMM connector pinout
Correct pinout for ETH
LED IOStandard set to LVCMOS33
BTN[0] IOStandard set to LVCMOS33
Changes are made based on Tang_primer_20K_3690 and Tang_Primer_20K-Dock_3709 schemes.
The patch tested with:
./sipeed_tang_primer_20k.py --cpu-type None --uart-name uartbone --csr-csv csr.csv --doc --with-etherbone --eth-ip 10.78.5.71 --build --load
[Tang_Primer_20K_Dock_3709_Schematics.pdf](https://github.com/litex-hub/litex-boards/files/10288234/Tang_Primer_20K_Dock_3709_Schematics.pdf)
[Tang_Primer_20K_Core_board_3690_Schematic.pdf](https://github.com/litex-hub/litex-boards/files/10288235/Tang_Primer_20K_Core_board_3690_Schematic.pdf)
> Correct pinout and IOStandard

- litex_boards/platforms/terasic_deca.py
- litex_boards/targets/terasic_deca.py
This pull request adds support for the integrated SD card socket on the DECA.
The board uses the SN74AVCA406L level shifter as an interface between the FPGA and the SD card. This means that some additional signals are necessary to set the direction of the command and data pins.
> terasic_deca: add SPI SD card support

- litex_boards/targets/lattice_crosslink_nx_vip.py
This was otherwise breaking this SoC
> nx_vip: Add missing 'origin' to SRAM SocRegions

- litex_boards/targets/digilent_arty.py
Only use XADC() and DNA() functions if vivado is the current toolchain.
I believe that this fixes #466 and https://github.com/chipsalliance/f4pga/issues/648
> Allow building digilent_arty using f4pga

- litex_boards/platforms/terasic_deca.py
The statements "derive_pll_clocks" and "derive_clock_uncertainty" are moved to the front of the additional sdc constraints list. The clocks generated by these statement can then be used in the additional sdc constraints.
> Avoid undefined clocks in generated sdc file

- litex_boards/platforms/opalkelly_xem8320.py
- litex_boards/prog/openocd_xcau25p_ft323.cfg
- litex_boards/targets/opalkelly_xem8320.py
Dependent on https://github.com/enjoy-digital/litex/pull/1625
This is a basic SoC for the Opal Kelly XEM8320.
It uses the SYZYGY PMOD expansion, PMOD SDcard, and PMOD video.
I plan to add the okHost HDL to allow for FrontPanel API for basic UART, data streaming, and debugging.
I also need to add a new loader to use the FrontPanel Selectmap config port.
FYI openOCD does not currently support this part.  I had to do a more complex cfg file for it.
> Basic SoC for Opal Kelly XEM8320

- litex_boards/platforms/sipeed_tang_nano_20k.py
- litex_boards/targets/sipeed_tang_nano_20k.py
This board uses Gowin GW2AR series chip (which is GW2A with integrated RAM).
Support for the integrated SDRAM on Tang Nano 20K is still TODO.
Note: currently when the SD card is enabled, block 0 could be correctly read but block 1 will fail.
==================
Depends on https://github.com/enjoy-digital/litex/pull/1646 .
> sipeed_tang_nano_20k: new board

- litex_boards/targets/sitlinv_stlv7325.py
As we do not need fine phase tweaking for the main system clock, use S7PLL instead of S7MMCM to allow higher VCO frequency and more flexible sys_clk_freq.
> sitlinv_stlv7325: use S7PLL instead of S7MMCM for system clock

- litex_boards/platforms/terasic_deca.py
This is now a working setup for DDR3 with UniPHY on the DECA board.
> make DDR3 memory work on the DECA with the UniPHY

- litex_boards/targets/xilinx_alveo_u200.py
I fixed the issue Memory initialization of Alveo U200 as discussed in https://github.com/enjoy-digital/litex/issues/1606.
Both offnaria and I confirmed that it works OK.
> Fix Memory initialization of Alveo U200 failed #1606

- litex_boards/targets/xilinx_alveo_u250.py
I had a memory test failure of AU250, the same as discussed in https://github.com/enjoy-digital/litex/issues/1606.
This is the log.
```
(c) Copyright 2012-2023 Enjoy-Digital
BIOS built on Apr 24 2023 17:48:49
BIOS CRC passed (23c21291)
LiteX git sha1: fb1cd22a
CPU:            VexRiscv @ 125MHz
BUS:            WISHBONE 32-bit @ 4GiB
CSR:            32-bit data
ROM:            128.0KiB
SRAM:           8.0KiB
L2:             8.0KiB
SDRAM:          16.0GiB 64-bit @ 1000MT/s (CL-9 CWL-9)
MAIN-RAM:       1.0GiB
Switching SDRAM to …
```
> Fix Memory test failure of Alveo U250

- litex_boards/platforms/sitlinv_stlv7325_v2.py
- litex_boards/targets/sitlinv_stlv7325_v2.py
This is the 2nd (2023) version of the board sold through https://www.aliexpress.us/item/3256801088848039.html
Link to the vendor-provided schematic: [XC7K325TFFG676-2原理图.pdf](https://github.com/litex-hub/litex-boards/files/11301409/XC7K325TFFG676-2.pdf)
> Initial support for STLV7325 (v2) Kintex-7 board.

- litex_boards/platforms/colorlight_i5a_907.py
- litex_boards/targets/colorlight_5a_75x.py
The [Colorlight i5a-907](https://www.colorlight-led.com/product/colorlight-i5a-907-led-display-receiving-card.html) is another LED receiver card close to the 5a-75x family.
This one has the advantage of having more 8 pins directly connected to the FPGA, making it a bit more convenient to use as a dev board then the other models.
**Todo**
```shell
python litex_boards/targets/colorlight_5a_75x.py --board=i5a-907 --revision=7.0 --build --load --with-etherbone
```
Etherbone test:
```shell
#> ping 192.168.1.50
PING 192.168.1.50 (192.168.1.50) 56(84) bytes of data.
64 bytes from 192.168.1.50: icmp_seq=1 ttl=128 time=0.912 ms
[...]
64 bytes from 192.168.1.50: icmp_seq=53 ttl=128 time=0.766 ms
^C
--- 192.168.1.50 ping statistics ---
53 packets transmitted, 53 received, 0% packet loss, time …
```
> Add colorlight i5a 907

- README.md
- litex_boards/platforms/alchitry_cu.py
- litex_boards/targets/alchitry_cu.py
Adding support for the Alchitry Cu. Board has a Lattice ICE40 HX8K CB132
I added the IO based on the board's schematic. I made the target based on the code for the icebreaker board. The SoC target works with a VexRiscv CPU lite variant, I was able to synthesise the design at 50MHz.
I new to the FPGA ecosystem and Litex. Let me know your comments, I'll make the changes
> alchitry_cu: add platform and target

- litex_boards/prog/openocd_evn_ecp5.cfg
- litex_boards/targets/lattice_ecp5_evn.py
This follows https://github.com/enjoy-digital/litex/pull/1087 which allows using the built-in JTAG for both the FPGA programming and the internal designs. Kuddos!
Starting LiteX server with it:
```
$ litex_server --jtag-config=targets/openocd.cfg --jtag
Open On-Chip Debugger 0.12.0+dev-g7023deb (2023-07-29-00:21)
Licensed under GNU GPL v2
For bug reports, read
http://openocd.org/doc/doxygen/bugs.html
jtagstream_serve
Info : ftdi: if you experience problems at higher adapter clocks, try the command "ftdi tdo_sam
ple_edge falling"
Info : clock speed 25000 kHz
Info : JTAG tap: ecp5.tap tap/device found: 0x81113043 (mfg: 0x021 (Lattice Semi.), part: 0x111
3, ver: 0x8)
Warn : gdb services need one or more targets defined
[CommUART] port: JTAG / tcp port: 1234
Connected with 127.0.0.1:40662 …
```
> lattice_ecp5_evn: add_jtagbone flag

- litex_boards/platforms/lattice_crosslink_nx_evn.py
- litex_boards/targets/lattice_crosslink_nx_evn.py
This goes along a small resistor jumper modification and firmware flashing like it is for the ECP5 board. A warning message is added as the default serial might be affected (--serial serial by default). The FTDI modification software used for the ECP5 seems to be requried and matching.
```
litex@lap1:$ targets/lattice_crosslink_nx_evn.py --csr-csv=csr.csv --toolchain=oxide --uart-name=crossover+uartbone --build --load
[...build logs with the extra message and 2s of wait time (sorry! open to suggestions)...]
litex@lap1:$
```
```
litex@lap1:$ litex_server --uart --uart-port /dev/ttyUSB0
[CommUART] port: /dev/ttyUSB0 / baudrate: 115200 / tcp port: 1234
Connected with 127.0.0.1:41364
Disconnect
Connected with 127.0.0.1:41366
Disconnect
Connected with 127.0.0.1:41382
Disconnect
Connected with …
```
> platforms/crosslink_nx_evn: allow use of UARTBone

- litex_boards/platforms/digilent_cmod_a7.py
- litex_boards/targets/digilent_cmod_a7.py
The default platform/target files for the Digilent Cmod A7 (https://digilent.com/reference/programmable-logic/cmod-a7/reference-manual) are not driving the `OE` pin on the ISSIRAM, so each read will fail and just return (0xFFFFFFFF), writes are working fine ( verified this with a scope ).
The ISSI documentation ( https://www.issi.com/WW/pdf/61-64WV5128Axx-Bxx.pdf?_ga=2.137274229.438686238.1691258285-1474693682.1688611108) clearly mentions the OE pin (as an active low signal) that needs to be driven low for reads.
According to the XDC provided by Digilent the `OE` pin is on **`P19`** ( Source: https://github.com/Digilent/digilent-xdc/blob/deb00e66689337700b3a18c0e3776dcf4a59655b/Cmod-A7-Master.xdc#L129 ) 
I just added the missing pin/subsignal definiton to the IO array in …
> Digilent CMOD A7 ISSIRAM fix

- litex_boards/targets/lattice_crosslink_nx_evn.py
This takes the values from the Antmicro SDI MIPI converter as a model and is enough to run a Zephyr hello world, but not seemingly enough for a the Zephyr Shell sample.
Related: https://github.com/litex-hub/zephyr-on-litex-vexriscv/pull/13
> targets/lattice_crosslink_nx_evn: add main_ram section for firmware

- litex_boards/platforms/lattice_crosslink_nx_evn.py
- litex_boards/prog/openocd_evn_nx.cfg
- litex_boards/targets/lattice_crosslink_nx_evn.py
This adds the support for Crosslink-NX EVN FTDI in JTAG mode, through OpenOCD.
This does not yet permit to use the JTAG for a serial connection with the bus (JTAGBone), as the `JTAG` instance is still not figured out, but hopefully I'll get there soon!
> Allow use of OpenOCD for the Crosslink-NX

- litex_boards/platforms/colorlight_i9plus.py
- litex_boards/targets/colorlight_i9plus.py
The [Colorlight i9+](https://controller-led.com/products/colorlight-i-series-led-display-controller-i9-i6-i5-led-receiving-card) is another LED receiver card, but contrary to the i5 family, this one is based on an ARTIX 7 FPGA.
It has some similarities with the i9 (same PHY and SDRAM) but a bigger FPGA and more available IOs.
**Todo**
> [init] added colorlight i9+ based on XC7A50 FPGA

- litex_boards/platforms/xilinx_zcu102.py
This resolves the following error during `build` on Vivado 2023.1:
``ERROR: [DRC BIVB-1] Bank IO standard Support: Bank 47 has incompatible IO(s) because: The LVDS I/O standard is not supported for banks of type High Density. Move the following ports or change their properties:
clk125_p``
> Resolve High Density bank IOStandard error

- litex_boards/platforms/sipeed_tang_mega_138k.py
- litex_boards/targets/sipeed_tang_mega_138k.py
Tagged RFC now because the board (and even the chip on my board) is still at ES stage.
> [RFC] sipeed_tang_mega_138k: new board

- litex_boards/platforms/sipeed_tang_primer_25k.py
- litex_boards/targets/sipeed_tang_primer_25k.py
sipeed tang primer 25k is based on:
- a core board with a gowin GW5A-25A (23k LUT) and an SPI flash
- a dock with a bl616 UART/JTAG interface, three leds (2 used for `ledChaser`), 3 buttons (2connected to the FPGA),  1 USB port, 3 PMOD and 1 2x30 pins.
Note: the BL616 seems have an issue with UART side -> tested LiteX bios with an external digilent UART PMOD.
> sipeed_tang_primer_25k: new board

- litex_boards/targets/siglent_sds1104xe.py
`siglent_sds1104xe` etherbone hybrid implementation is similar to `add_etherbone` and subclass. With [commit](https://github.com/enjoy-digital/litex/commit/bf3286f564d92b03925f68d3757f182257e75131) it's become possible to remove this code and use directly `add_etherbone` with interface == *hybrid*.
> targets/siglent_sds1104xe: simplify etherbone by using new etherbone's params to specify hybrid mode

- litex_boards/platforms/qmtech_artix7_fbg484.py
- litex_boards/platforms/qmtech_artix7_fgg676.py
- litex_boards/platforms/qmtech_wukong.py
- litex_boards/platforms/qmtech_xc7a35t.py
- litex_boards/platforms/qmtech_xc7k325t.py
I also removed setting .f4pga_device since it is identical to platform.device
> QMTech boards: make Artix7 bitstream/platform commands conditional on toolchain

- litex_boards/platforms/terasic_de2_115.py
- litex_boards/targets/terasic_de2_115.py
This PR adds additional peripherals to the Terasic DE2-115 board support files, such as 2 MII Ethernet ports, SD card and on-board LEDs
> Improve terasic_de2_115 target support

- litex_boards/platforms/aliexpress_xc7k70t.py
- litex_boards/targets/aliexpress_xc7k70t.py
https://www.aliexpress.com/item/1005005572549665.html
```
(c) Copyright 2012-2023 Enjoy-Digital
BIOS built on Nov  9 2023 10:28:08
BIOS CRC passed (7ebd4500)
LiteX git sha1: f3f46e8c
CPU:		VexRiscv @ 90MHz
ROM:		128.0KiB
SRAM:		8.0KiB
L2:		8.0KiB
SDRAM:		16.0MiB 16-bit @ 90MT/s (CL-2 CWL-2)
MAIN-RAM:	16.0MiB
Read: 0x40000000-0x40200000 …
```
> Add AliExpress Kintex XC7K70T board

- litex_boards/platforms/sipeed_tang_mega_138k.py
- litex_boards/targets/sipeed_tang_mega_138k.py
This PR contains 2 commits:
- the first address DDR3: fix `DRIVE=XX` by adding for each `Subsignal` adapted value, it also remove `a[15]` (unused for these chips), and change module to have something nearest real chip
- the second moves ethernet pinout to the dock_io part
> Tang mega138k p2

- litex_boards/platforms/sipeed_tang_mega_138k.py
I added few more pins (that I use for some projects) to tang-mega platform.
I also added `use_ready_as_gpio` and `use_done_as_gpio` to toolchain options, which allows to use two LEDs in the SOM board as well (here mapped as `led_done` and `led_ready`)
> sipeed_tang_mega_138k: Added PCIe reset and other pins from sipeed dock

- litex_boards/platforms/qmtech_xc7k325t.py
I forgot to enable this one!
Important for such a large part.
> Enable bitstream compression on Kintex K325T

- litex_boards/platforms/digilent_basys3.py
I spent quite some time scratching my head why i got no picture from litex when all looked good and the default basys example produced a very crisp picture.. Until i found this!
And an open question: i notice there are no defines either for the onboard flash or the 4x7 segment, should i add these? perhaps in a separate PR?
> Correct pinout for VGA connector

- litex_boards/platforms/sqrl_acorn.py
The cle-101 (and the litfury) is a xc7a100t, but we were using the wrong proxy bitstream when flashing
> Fix sqrl_acorn proxy bitstream for cle-101

- litex_boards/targets/qmtech_artix7_fbg484.py
- litex_boards/targets/qmtech_artix7_fgg676.py
I wondered why the second byte did not pass memtest on MiSTeX,
and comparing with the Wukong you just tested, I found that
those boards actually used the wrong memory chip type.
> qmtech_artix7_fgg676/fbg484: fix wrong memory chip type

- litex_boards/platforms/qmtech_10cl006.py
- litex_boards/platforms/qmtech_5cefa2.py
- litex_boards/platforms/qmtech_5cefa5.py
- litex_boards/platforms/qmtech_ep4cex5.py
- litex_boards/platforms/qmtech_ep4cgx150.py
- litex_boards/platforms/qmtech_xc7a35t.py
- litex_boards/platforms/qmtech_xc7k325t.py
This makes derivative designs (like MiSTeX) more flexible.
> qmtech core boards: make core resources optional

- litex_boards/platforms/qmtech_10cl006.py
- litex_boards/platforms/qmtech_5cefa2.py
- litex_boards/platforms/qmtech_5cefa5.py
- litex_boards/platforms/qmtech_ep4cex5.py
- litex_boards/platforms/qmtech_ep4cgx150.py
- litex_boards/targets/qmtech_5cefa5.py
- litex_boards/targets/qmtech_ep4cgx150.py
```
(c) Copyright 2012-2024 Enjoy-Digital
BIOS built on Mar 30 2024 20:12:42
BIOS CRC passed (796e7126)
LiteX git sha1: 87137c30
CPU:		VexRiscv @ 95MHz
BUS:		wishbone 32-bit @ 4GiB
ROM:		128.0KiB
SRAM:		8.0KiB
L2:		8.0KiB
SDRAM:		64.0MiB 32-bit @ 95MT/s (CL-2 CWL-2)
MAIN-RAM:	64.0MiB
Read: 0x40000000-0x40200000 2.0MiB     
Memtest OK
Memspeed at 0x40000000 …
```
> Better Altera SDRAM IO properties for more speed

- litex_boards/platforms/alientek_davincipro.py
- litex_boards/targets/alientek_davincipro.py
```       __   _ __      _  __
(c) Copyright 2012-2024 Enjoy-Digital
BIOS built on Apr 22 2024 13:05:07
BIOS CRC passed (16928465)
LiteX git sha1: dc78c3f4
CPU:		VexRiscv @ 100MHz
BUS:		wishbone 32-bit @ 4GiB
ROM:		128.0KiB
SRAM:		8.0KiB
L2:		8.0KiB
SDRAM:		512.0MiB 32-bit @ 800MT/s (CL-7 CWL-5)
MAIN-RAM:	512.0MiB
Ethernet init...
Read leveling:
m0, b00: |00000000000000000000000000000000| delays: -
m0, b01: |00000000000000000000000000000000| delays: -
m0, b02: |11111111111100000000000000000000| …
```
> Add Alientek DaVinci Pro FPGA board

- litex_boards/platforms/efinix_trion_t20_bga256_dev_kit.py
- litex_boards/targets/efinix_trion_t20_bga256_dev_kit.py
add sdram of the efinix trion t20 bga256 dev kit.
The sdram will only work, if the system clock frequency is not bigger than 50 MHz.
When the spiflash is also activated, the sdram will fail partly with any system frequency of 50 MHz, that's why the default had been lowered to 45 MHz, because at that frequency it works.
> efinix_trion_t20: add sdram

- litex_boards/targets/alinx_axu2cga.py
- litex_boards/targets/digilent_arty_z7.py
- litex_boards/targets/digilent_pynq_z1.py
- litex_boards/targets/digilent_zedboard.py
- litex_boards/targets/krtkl_snickerdoodle.py
- litex_boards/targets/redpitaya.py
- litex_boards/targets/xilinx_kv260.py
- litex_boards/targets/xilinx_zcu216.py
- litex_boards/targets/xilinx_zybo_z7.py
With this [PR](https://github.com/enjoy-digital/litex/pull/1994) CSR are now defined at CPU core level and the first CPU interface is automatically connected to the SoC. This allows to reduces logic at target level and behavior is now nearest as others CPUs.
Tested using zedboard, artyZ7 and ZCU102.
> ZynqXXX boards: remove CSR definition and GP0 connection to CPU

- README.md
- litex_boards/platforms/machdyne_konfekt.py
- litex_boards/platforms/machdyne_kopflos.py
- litex_boards/platforms/machdyne_lakritz.py
- litex_boards/platforms/machdyne_minze.py
- litex_boards/platforms/machdyne_mozart_ml1.py
- litex_boards/platforms/machdyne_mozart_ml2.py
- litex_boards/platforms/machdyne_mozart_mx1.py
- litex_boards/platforms/machdyne_noir.py
- litex_boards/platforms/machdyne_schoko.py
- litex_boards/platforms/machdyne_vanille.py
- litex_boards/platforms/machdyne_vivaldi_ml1.py
- litex_boards/targets/machdyne_konfekt.py
- litex_boards/targets/machdyne_lakritz.py
- litex_boards/targets/machdyne_minze.py
- litex_boards/targets/machdyne_mozart_ml1.py
- litex_boards/targets/machdyne_mozart_ml2.py
- litex_boards/targets/machdyne_mozart_mx1.py
- litex_boards/targets/machdyne_noir.py
- litex_boards/targets/machdyne_vanille.py
- litex_boards/targets/machdyne_vivaldi_ml1.py
This PR fixes some typos in the Machdyne platform files and adds support for the [Vanille](https://github.com/machdyne/vanille) and [Lakritz](https://github.com/machdyne/lakritz) FPGA computers.
> machdyne: fix typos; add vanille and lakritz

- litex_boards/platforms/sipeed_tang_primer_20k.py
As mentioned in *led*'s comment  `IOStandard` have a wrong value.
This PR fix the value for all resources.
It also disable and adds a not for *i2c* pins for HDMI and LCD due to a conflict with ethernet.
> platforms/sipeed_tang_primer_20k.py: fix IOStandard values

- litex_boards/targets/efinix_titanium_ti60_f225_dev_kit.py
- litex_boards/targets/efinix_trion_t120_bga576_dev_kit.py
This PR has two goals:
- allowing user to provides remote ip
- honour eth_ip for both add_ethernet/add_etherbone (currently eth_ip is unused)
> Efinix eth ip

- litex_boards/targets/efinix_trion_t120_bga576_dev_kit.py
With commit https://github.com/litex-hub/litex-boards/commit/7f26f3940f78fb804fa3295ac79bec40e8e945f6 a workaround has been applied for efinix_trion_t120_bga576_dev_kit.py target board to use onboard RGMII 0.
Currently users must modify target to switch between PMOD RMII and onboard RGMII.
This PR adds an argument to let user select the phy without having to modify target file.
> targets/efinix_trion_t120_bga576_dev_kit.py: added argument to select between RMII PMOD (default) or onboard RGMII Phy

- litex_boards/targets/sipeed_tang_nano.py
- litex_boards/targets/sipeed_tang_nano_20k.py
- litex_boards/targets/sipeed_tang_nano_4k.py
- litex_boards/targets/sipeed_tang_nano_9k.py
- litex_boards/targets/sipeed_tang_primer_20k.py
- litex_boards/targets/sipeed_tang_primer_25k.py
Thanks to https://github.com/enjoy-digital/litex/pull/2036 by @Mai-Lapyst LiteX supports Apicula with the Himaechel target now, but it appears that the boards do not yet work correctly.
This is a WIP PR to try and fix those. I figured I'd put it out there to avoid duplicating work with Mai.
So far I've been mostly threading `toolchain`  through to the platform. Currently it fails to connect the RAM chips with their SERDES and SiP IO stuff. Some of that may be a more long-term project.
Depends on https://github.com/enjoy-digital/litex/pull/2042
> make Gowin boards work with Apicula

- litex_boards/targets/efinix_trion_t120_bga576_dev_kit.py
- litex_boards/targets/efinix_trion_t20_bga256_dev_kit.py
With [PR]( https://github.com/enjoy-digital/litex/pull/2060) create_clkout's name parameter is not more used when a cd is provided: DDRAM clock name must be obtained by using name_override attribute from sys_clk clk signal.
> targets/efinix_trion_t120_bga576_dev_kit.py: fix clock name to match sys_clk real name

- litex_boards/platforms/efinix_ti375_c529_dev_kit.py
- litex_boards/platforms/efinix_titanium_ti60_f225_dev_kit.py
- litex_boards/targets/efinix_ti375_c529_dev_kit.py
Don't merge before : 
- https://github.com/enjoy-digital/litex/pull/2060
- https://github.com/enjoy-digital/litex/pull/2059
This is the port i'm using mostly to run VexiiRiscv + Debian.
Typicaly with : 
--cpu-type=vexiiriscv --cpu-variant=debian --update-repo=no --with-jtag-tap --with-sdcard --with-coherent-dma --with-ohci --vexii-video "name=video" --vexii-args="--fetch-l1-hardware-prefetch=nl --fetch-l1-refill-count=2 --fetch-l1-mem-data-width-min=128 --lsu-l1-mem-data-width-min=128 --lsu-software-prefetch --lsu-hardware-prefetch rpt --performance-counters 9 --lsu-l1-store-buffer-ops=32 --lsu-l1-refill-count 4 --lsu-l1-writeback-count 4 --lsu-l1-store-buffer-slots=4 --relaxed-div" --l2-bytes=524288 --sys-clk-freq 100000000 --cpu-clk-freq 200000000 --with-cpu-clk --bus-standard axi-lite …
> Add efinix Ti375 c529 dev kit support

- litex_boards/platforms/signaloid_c0_microsd.py
- litex_boards/targets/signaloid_c0_microsd.py
This PR adds support for the Signaloid C0-microSD FPGA SoM, which is based on the Lattice iCE40 chip.
For more details on the device please refer to:
- [Documentation Page](https://c0-microsd-docs.signaloid.io/)
- [GitHub home page](https://github.com/signaloid/C0-microSD-Hardware)
> Add support for Signaloid C0-microSD

- README.md
- litex_boards/platforms/digilent_netfpga_sume.py
- litex_boards/targets/digilent_netfpga_sume.py
Tasks:
Tests with CPUs (125Mhz):
> Add support for NetFPGA-Sume

- litex_boards/platforms/efinix_t8f81_dev_kit.py
- litex_boards/platforms/efinix_titanium_ti60_f225_dev_kit.py
- litex_boards/platforms/efinix_trion_t120_bga576_dev_kit.py
- litex_boards/platforms/efinix_trion_t20_bga256_dev_kit.py
- litex_boards/platforms/efinix_trion_t20_mipi_dev_kit.py
- litex_boards/platforms/efinix_xyloni_dev_kit.py
- litex_boards/platforms/jungle_electronics_fireant.py
- litex_boards/targets/efinix_t8f81_dev_kit.py
- litex_boards/targets/efinix_ti375_c529_dev_kit.py
- litex_boards/targets/efinix_titanium_ti60_f225_dev_kit.py
- litex_boards/targets/efinix_trion_t120_bga576_dev_kit.py
- litex_boards/targets/efinix_trion_t20_bga256_dev_kit.py
- litex_boards/targets/efinix_trion_t20_mipi_dev_kit.py
- litex_boards/targets/efinix_xyloni_dev_kit.py
- litex_boards/targets/jungle_electronics_fireant.py
fix reset on all efinix boards.
To reset the PLL a pulse is needed, which
has to be driven by a clock that is
not generated by the PLL.
> efinix: fix reset

- litex_boards/platforms/embedfire_rise_pro.py
- litex_boards/targets/embedfire_rise_pro.py
Tested: 
Test With CPUs (50Mhz) :
> Add support for embedfire rise pro

- litex_boards/targets/efinix_trion_t20_mipi_dev_kit.py
this fixes the --flash argument for the efinix T20 mipi devkit (was just missing a few parse lines)
> simple flash fix for the efinix T20 MIPI DK

- litex_boards/targets/digilent_genesys2.py
As mentioned in #624 `--toolchain` argument is ignored by `digilent_genesys2.py` target.
This PR adds a CTOR's parameters to propagates this argument to the platform.
Warning: A review/test is required due to the lack of opencx7 on my computer.
> targets/digilent_genesys2.py: added toolchain option (#624)

- litex_boards/platforms/sipeed_tang_nano_20k.py
- litex_boards/targets/sipeed_tang_nano_20k.py
- SPI flash support, using compatible IC
- HDMI support
- `--with-rgb-led` is fixed in <https://github.com/enjoy-digital/litex/pull/2142>
SPI flash log:
```text
Initializing w25q64 SPI Flash @0x00800000...
First SPI Flash block erased, unable to perform freq test.
Memspeed at 0x800000 (Sequential, 4.0KiB)...
Read speed: 1.1MiB/s
Memspeed at 0x800000 (Random, 4.0KiB)...
Read speed: 674.3KiB/s
```
> sipeed_tang_nano_20k: add SPI flash and HDMI support

- litex_boards/platforms/alibaba_vu13p.py
- litex_boards/targets/alibaba_vu13p.py
Alibaba VU13P board was designed for Alibaba Cloud FPGA instance and DPUs.
Those boards are appearing in used market (about 5000 CNY) and hobbyists managed to reverse engineering pinout.
PCIe, DDR, Ethernet were all tested to be working.
Note that ethernet depends on: https://github.com/enjoy-digital/liteeth/pull/178
Boot log with etherbone:
```
(c) Copyright 2012-2024 Enjoy-Digital
BIOS built on Dec 16 2024 16:01:22
BIOS CRC passed (f5b548c8)
LiteX git sha1: ec06bf595
CPU:            VexRiscv @ 125MHz
BUS:            wishbone 32-bit @ 4GiB
CSR:            32-bit data
ROM:            128.0KiB
SRAM: …
```
> Add support for Alibaba VU13P

- litex_boards/platforms/lckfb_ljpi.py
- litex_boards/targets/lckfb_ljpi.py
LCKFB LJPI is a GW2A-LV18 board by LCSC.
LCKFB means "Develop Boards by LCSC".
LJPI(逻辑派) means "Logic Pi" in Chinese.
The document is available at https://wiki.lckfb.com/zh-hans/fpga-ljpi/ (Chinese Version).
The openFPGALoader support is not finished yet. Gowin programmer works.
(As Gowin has already released the macOS version of GowinEDA/Programmer, this is not a problem).
Upstream Gowin Programmer support is merged at <https://github.com/enjoy-digital/litex/pull/2147>.
Verified on my board.
> lckfb_ljpi: Add support for LCKFB LJPI

- litex_boards/platforms/efinix_ti375_c529_dev_kit.py
This adds the pinout of the FMC LPC connector on the Efinix Ti375 C529 Dev-Kit.
> Efinix Ti375 C529 Dev-Kit: Add FMC LPC connector

- litex_boards/platforms/colorlight_5a_75b.py
- litex_boards/targets/colorlight_5a_75x.py
Based on https://github.com/q3k/chubby75/blob/master/5a-75b/hardware_V8.2.md it appears that the pinout v8.0 is the same as the v8.2, the only difference is the FPGA - a Lattice ECP5 LFE5U-25F-7BG256I
The SDRAM for the 8.0 and 8.2 is the same, but the CLS was not being correctly set, this commit also corrects this.
Tested on a v8.2 board using https://github.com/enjoy-digital/colorlite
Fixes #574
> Add in colorlight v8.2 board support

- litex_boards/platforms/efinix_ti375_c529_dev_kit.py
This fixes the pinout from the previous PR (#636), as that one accidentally used the FMC pin names, rather than the FPGA ones.
> Efinix Ti375 C529 Dev-Kit: Fix FMC LPC pinout

- README.md
- litex_boards/platforms/sipeed_tang_console.py
- litex_boards/targets/sipeed_tang_console.py
This is a first draft for [Sipeed Tang Console](https://wiki.sipeed.com/hardware/zh/tang/tang-console/mega-console.html)
This is a baseboard supporting TangMega 60k & TangMega 138k. This PR adds requirements for 60k flavor.
Missing peripherals:
- USB x 3
- 2nd DDR3 chip
- sdram1_connector
Peripherals:
> added support for Sipeed Tang Console

- litex_boards/platforms/radiona_ulx3s.py
This pull request is connected with the[ pull request](https://github.com/enjoy-digital/litex/pull/2183) I made on Litex regarding the use of `fujprog` instead of `ujprog` for progamming the ULX3S board.
Here I just changed the `radiona_ulx3s.py` file to import  and use `fujprog` instead of `ujprog`.
> Changed the programmer to fujprog on ULX3S

- litex_boards/targets/lattice_certuspro_nx_versa.py
Only PCIe is tested
Depends on https://github.com/enjoy-digital/litepcie/pull/145
> targets/lattice_certuspro_nx_versa.py: added basic target: Leds and PCIe

- litex_boards/platforms/sqrl_acorn.py
- litex_boards/targets/litex_acorn_baseboard_mini.py
The *litex_acorn_baseboard_mini* target provides a custom `Platform` inheriting from *platforms/sqrl_acorn.py* to re-implement the `create_programmer` method. But, unlike *sqrl_acorn* this variant only suppport CLE-215(+), CLE-101 is not supported.
This PR:
- removes the custom Platform to directly uses `sqrl_acorn/Platform`
- `sqrl_acorn.py` platform supports both `OpenOCD` and `OpenFPGALoader` as programmer tool. A new argument is added to allows user selecting the tool (`OpenOCD` is the default value to keep original behavior)
> targets/litex_acorn_baseboard_mini.py: removed obsolete Platform override. Added parameter to select programmer tool

- litex_boards/platforms/efinix_ti375_c529_dev_kit.py
- litex_boards/targets/efinix_ti375_c529_dev_kit.py
* Added definitions for five user LEDs to the `efinix_ti375_c529_dev_kit.py` platform file.
* Added a `--flash` argument to the `generate` method in the `efinix_ti375_c529_dev_kit.py` target file to support flashing the bitstream.
> efinix_ti375_c529_dev_kit: add flash function

- litex_boards/platforms/sqrl_acorn.py
Commit 1b22061e93b2add0132cfbcd10ca0e9977a163b2 has changed PCIe `rst_n` IOStandard: before 3.3V, now 1.5V.
But the BANK35 is 3.3V, LEDs are configured in 3.3V and Vivado fails due to a conflict between IOs.
This is true for `pcie_x4` but baseboard `pcie_x1` is correctly set to 3.3V
This PR changes `pcie_x4` definition to avoid build failure.
> platforms/sqrl_acorn.py: fixed pcie_x4 rst_n IOStandard: BANK35 is 3.3V (conflict with LEDs)

- .github/workflows/ci.yml
Since 2025-04-15, ubuntu 20.04 is removed and the run CI is cancelled.
This PR bump ubuntu version to 22.04, no others modifications (python is kept in 3.9 version).
> CI: update ubuntu to 22.04

- litex_boards/platforms/bochenjingxin_kintex7_basec.py
- litex_boards/targets/bochenjingxin_kintex7_basec.py
This PR adds an initial support for Kintex-7 Base C board, mentioned in #648.
Current status:
- I use openxc7 as the toolchain, because I don't have a paid Vivado license for xc7k325t.
- While the board has xc7k325tffg676-2, I use -1 speed grade to adapt openxc7's constraint.
- The SoC lacks several peripherals, such as DRAM, for now.
Thank you.
> Initial support for Kintex-7 Base C board.

- litex_boards/targets/colognechip_gatemate_evb.py
- litex_boards/targets/olimex_gatemate_a1_evb.py
PR https://github.com/enjoy-digital/litex/pull/2237 introduces opensource toolchain for CologneChip GateMate FPGAs.
This PR updates `olimex_gatemate_a1_evb` and `colognechip_gatemate_evb` targets to allows users select between colognechip and peppercorn toolchains.
> Colognechip peppercorn toolchain

- litex_boards/platforms/aliexpress_xc7k70t.py
- litex_boards/platforms/hyvision_pcie_opt01_revf.py
- litex_boards/targets/hyvision_pcie_opt01_revf.py
Add support for these Kintex7 boards, which are cheaply available
on ebay:
https://www.ebay.com/sch/i.html?_nkw=hyvision+pcie
Question: When I try to build it, I get an obscure error when building the DDR software driver. Is that a litedram problem,
or did I get something wrong here?
```
INFO:S7MMCM:Creating S7MMCM, speedgrade -1.
INFO:S7MMCM:Registering Differential ClkIn of 200.00MHz.
INFO:S7MMCM:Creating ClkOut0 sys of 100.00MHz (+-10000.00ppm).
INFO:S7MMCM:Creating ClkOut1 sys2x of 200.00MHz (+-10000.00ppm).
INFO:S7MMCM:Creating ClkOut2 sys2x_dqs of 200.00MHz (+-10000.00ppm).
INFO:S7MMCM:Creating ClkOut3 idelay of 200.00MHz (+-10000.00ppm).
INFO:SoC:        __   _ __      _  __  
INFO:SoC:       / /  (_) /____ | |/_/  
INFO:SoC:      / /__/ / __/ -_)>  <    
INFO:SoC: …
```
> Add Support for HyVision

- litex_boards/platforms/hyvision_pcie_opt01_revf.py
- litex_boards/targets/hyvision_pcie_opt01_revf.py
It's a WIP to fix / updates some peripherals:
- Fixed *DDR2* `BA` pins order
- Added `SFP`/`ethernet`/`etherbone` support in the target
Notes:
- a 156.26M oscillator is available for SFP via pin `H6` but `K7_1000BASEX` PHY only support 200MHz clock frequency
Tests:
- PCIe tested: OK
- SFP 0/1 tested: OK
- DDR2: KO (When only the first chip is used memtest result is OK)
> Hyvision pcie opt01 revf fix update

- README.md
- litex_boards/platforms/mlkpai_fs01_dr1v90m.py
- litex_boards/targets/mlkpai_fs01_dr1v90m.py
Introduce MLKPAI-FS01-DR1V90M, powered by DR1V90MEG484 from Anlogic, which has built-in FPGA with 94464 LUTs and a UX900 RISC-V CPU hardcore from Nuclei System Technology. The dr1_90 architecture is only supported in Tang Dynasty version 5.9 currently.
Peripherals support:
- 25M clk
- 8 leds
- 3 buttons
- 1 on-board USB-C serial
This depends on https://github.com/enjoy-digital/litex/pull/2242
> Add mlkpai-fs01-dr1v90m board support

- README.md
- litex_boards/platforms/alinx_ax7203.py
- litex_boards/targets/alinx_ax7203.py
Add support for the AX7203 FPGA development board equipped with the AMD Artix 7 series device.
https://en.alinx.com/Product/FPGA-Development-Boards/Artix-7/AX7203.html
> alinx_ax7203: Add AX7203 FPGA development board

- litex_boards/platforms/machdyne_kolsch.py
- litex_boards/targets/machdyne_kolsch.py
This one requires to be applied as well
https://github.com/enjoy-digital/litedram/pull/366
https://github.com/enjoy-digital/litex/pull/2274
> Add support for Machdyne Kolsch

- litex_boards/platforms/alinx_ax7203.py
- litex_boards/targets/alinx_ax7203.py
This pull request enhances the functionality of the `alinx_ax7203` platform by adding support for HDMI video output and updating existing features. 
* Integrated HDMI video output into the SoC in `litex_boards/targets/alinx_ax7203.py`, including the `VideoDVIPHY` for HDMI PHY and `I2CMaster` for video initialization.
* Enabled configuration for video framebuffer support through a new `--with-video-framebuffer` argument in the `main()` function.
> alinx_ax7203: Add HDMI support to AX7203 FPGA development board

- litex_boards/platforms/xilinx_kcu116.py
- litex_boards/targets/xilinx_kcu116.py
This is a PR for the Xilinx KCU116
https://www.amd.com/en/products/adaptive-socs-and-fpgas/evaluation-boards/ek-u1-kcu116-g.html
The files are adaptations of the KCU105-files.
Current status:
- Tested with VexRiscv
- Tested Features:
-  CLK-Inputs: 300MHz, USER_MGT_CLK (for Ethernet)
- CPU-Reset-Button
- Leds, Buttons
- Serial
- DDR4
- SFP-Ethernet
Thx for reviewing
> Initial support for Xilinx KCU116

- litex_boards/platforms/colorlight_5a_75e.py
This is a fix of mistake in J13 connector description for Colorlight 5A-75e v8.2 board
> Fix typo in connectors for Colorlight 5A-75e

- litex_boards/targets/arrow_axe5000.py
Align with litex pull-request #2334 [1], Agilex5PLL now requires platform reference to correctly produce SDC constraints.
[1] https://github.com/enjoy-digital/litex/pull/2334
> targets/arrow_axe5000: fix call to Agilex5PLL after litex core changes

- litex_boards/targets/sipeed_tang_nano_20k.py
This PR fixes two issues with `sipeed_tang_nano_20.py` target related to HDMI:
- unlike some others *sipeed* boards, pairs used for HDMI are true differential. As mentioned in https://github.com/enjoy-digital/litex/pull/2341, a `TLVDS_OBUF` must be used otherwise *apicula* fails. the above mentioned PR has introduces the `true_lvds` CTOR's parameter for `VideoGowinHDMIPHY` to select between primitives. The first commit simply sets this parameter to `True` to uses the good primitive
- Second commit is related to `add_video_colorbars`: HDMI ClockDomain, at `CRG` level, is configured to have a pix_clk == 25MHz, but timings parameter is fixed to `800x600@60Hz` requiring a 40MHz. By switching `timings` to `640x480@60Hz` the colorbars mode is now working.
> Tang nano 20k hdmi fix
