setup.py
=> Add litex_boards package to setup.py

setup.py
=> Turn litex_boards.partner into module

litex_boards/community/platforms/trellisboard.py, litex_boards/community/targets/trellisboard.py
See https://github.com/daveshah1/TrellisBoard
=> community: Add TrellisBoard

litex_boards/partner/targets/ulx3s.py
I have 4 of these boards now.  3 that I've bought from Radiona and one that I made myself and between them they have 3 different SDRAM parts.  It's only a two-line change currently to switch between parts, but having an argument switch is a nice convenience.
If your board had something else on-board all you would have to do is extend the import statement to include your part number.
If pass an invalid / unsupported part number you get a message like: ```AttributeError: module '__main__' has no attribute 'AS4C16M16F'```
=> memory device selection for ulx3s

litex_boards/official/platforms/versa_ecp5.py, litex_boards/official/targets/arty.py, litex_boards/official/targets/nexys4ddr.py, litex_boards/official/targets/versa_ecp5.py, litex_boards/partner/targets/trellisboard.py
sync up some of the platforms and targets to their latest LiteX equivalents
=> Gls sync litex

litex_boards/community/platforms/pipistrello.py, litex_boards/community/targets/pipistrello.py
This is s a rough, first try to run Linux on the board. Files are taken from litex-buildenv and re-adapted.
=> Adding initial support for Saanlima's Pipistrello LX45 board

litex_boards/community/platforms/de10nano.py, litex_boards/community/targets/de10nano.py
I'm not really sure what I'm doing here at all. I wrote this, ran the targets/de10nano.py, that generated an rbf, which I uploaded to the de10 nano, and it echoes back serial. Does that sound about right?
=> Add de10 nano board

litex_boards/targets/fomu.py
With the last commit this file was dependent on the previous folder structure.
=> Changed wrong imports for fomu board.

litex_boards/platforms/ecp5_evn.py
Depends on https://github.com/enjoy-digital/litex/pull/444
=> programming the ECP5-EVN flash through the OpenOCD JTAG-SPI proxy

litex_boards/platforms/artys7.py, litex_boards/targets/artys7.py
As the pin-out is totally different from the A7 board I did put this
in a separate class and not as a variant of the Arty board.
Used migen Arty S7 board file and Digilent xdc file as reference.
=> Added Arty S7 board

litex_boards/platforms/colorlight_5a_75b.py, litex_boards/platforms/ulx3s.py, litex_boards/targets/README.colorlight_5a_75b, litex_boards/targets/README.ulx3s, litex_boards/targets/bit_to_flash.py, litex_boards/targets/colorlight_5a_75b.py, litex_boards/targets/ulx3s.py
Additions for USB support based on Gregs' valentyusb.
=> Addition of USB ACM for ECP5

litex_boards/platforms/ecp5_evn.py
Added spiflash1x pins, a method to create an SpiFlash instance and a note on a second UART channel of FT2232H
=> ECP5-EVN SpiFlash parameters

litex_boards/platforms/de10nano.py, litex_boards/targets/de10nano.py
Change from 32mb to 128mb mister sdram, uart via usb-lookalike port on mister i/o board, vga via i/o board, 8 user leds, and light up the mister case leds
=> Use 128mb sdram, uart via i/o port on i/o board and vga terminal via i/o board

litex_boards/targets/minispartan6.py
This PR is a part of https://github.com/enjoy-digital/litedram/pull/206.
=> targets/minispartan6: add support for HalfRateGENSDRPHY

litex_boards/platforms/colorlight_5a_75e.py, litex_boards/targets/colorlight_5a_75x.py
...though it is not working with Ethernet for me, yet.
When I try current consumption goes way down and nothing happens. Except for I can probe a weird 2.5MHz clock at the SDRAM.
Does anybody have an idea?
=> Add support for 5A-75E V6.0 board

litex_boards/platforms/crosslink_nx_evn.py, litex_boards/targets/crosslink_nx_evn.py
Make the requirement a bit clearer, particularly in light of a typo in the user guide.
=> crosslink_nx_evn: Improve documentation on UART jumpers

litex_boards/targets/versa_ecp5.py
Etherbone can be enabled with --with-etherbone
=> versa_ecp5: Add etherbone support

litex_boards/targets/versa_ecp5.py
This also simplifies the logic a bit.
=> versa_ecp5: Add --eth-phy to select ethernet phy

litex_boards/platforms/crosslink_nx_evn.py, litex_boards/targets/crosslink_nx_evn.py
Adding support for the PLL blocks in the Lattice NX chips. This should be accepted alongside [this PR](https://github.com/enjoy-digital/litex/pull/692).
=> Lattice NX PLL Support

litex_boards/platforms/crosslink_nx_evn.py, litex_boards/platforms/crosslink_nx_vip.py, litex_boards/targets/crosslink_nx_evn.py, litex_boards/targets/crosslink_nx_vip.py
Please see the caveats in enjoy-digital/litex#709 - for the reasons mentioned there the only working combo ATM is VIP+hyperram
=> nexus: Allow selection of toolchain

litex_boards/platforms/arty.py, litex_boards/targets/arty.py
This PR updates the Arty Board description in the `litex-boards` to match with the version used in the main LiteX repository.
=> Sync Arty Board files with main LiteX repository

litex_boards/targets/nexys4ddr.py
add etherbone (and `--with-etherbone` command line argument) to nexys4ddr.
=> nexys4ddr: add etherbone support

litex_boards/platforms/arrow_sockit.py, litex_boards/platforms/de0nano.py, litex_boards/targets/arrow_sockit.py
Hi Florent,
today I got a first running version that blinks the LEDs on the board.
There are still quite a number of things missing (DDR3 not possible because literam does not support altera yet
and no hard CPU core support),
but it is already in a useable state, and worthy to share.
The different commits are probably of not much interest to the history, so you might want to squash
all detailed commits.
Does github have a checkbox for squashing commits on merge, or do you want me to squash?
Best regards,
Hans
=> Add board support for Terasic/Arrow SocKit, Add connectors to de0-nano

litex_boards/platforms/fpc_iii.py, litex_boards/prog/openocd_fpc_iii.cfg, litex_boards/targets/fpc_iii.py
Please note this depends on https://github.com/enjoy-digital/litevideo/pull/36 and https://github.com/enjoy-digital/litex/pull/787.
=> Add FPC-III board support.

litex_boards/platforms/nexys_video.py, litex_boards/targets/nexys_video.py
Signed-off-by: Jan Kowalewski <jkowalewski@antmicro.com>
These changes weren't tested on HW however it is possible to generate the gateware with the symbiflow toolchain option
Depends on: https://github.com/enjoy-digital/litex/pull/799
=> nexys_video: enable symbiflow toolchain

README.md, litex_boards/platforms/deca.py, litex_boards/targets/deca.py, test/test_targets.py
Hi I just added support for this board.
=> Add board support for Terasic/Arrow DECA board (Intel Max10)

litex_boards/targets/digilent_nexys_video.py
The VADJ value changes the resistance to set the voltages for the FMC expansion board. Therefore, depending on the FMC expansion board we need to be able to modify the VADJ value when building the nexys_video target.
This PR adds the `--vadj` argument to choose this value.
=> nexys_video: choose VADJ value with arguments

litex_boards/platforms/terasic_deca.py, litex_boards/targets/terasic_deca.py
Some fixes/enhancements to the DECA board.
=> terasic_deca: fix cable name, ulpi, names, add gpio_serial

litex_boards/targets/ztex213.py
Otherwise the variant is ignored...
=> ztex213 fix; propagate variant from targets to platform

litex_boards/__init__.py
=> boards/compat: Skip targets with unsatisfied dependencies.

litex_boards/targets/digilent_arty.py
Signed-off-by: Karol Gugala <kgugala@antmicro.com>
=> arty: add option to use litespi QSPI controller

README.md, litex_boards/platforms/muselab_icesugar.py, litex_boards/targets/muselab_icesugar.py, test/test_targets.py
```
(c) Copyright 2012-2021 Enjoy-Digital
BIOS built on May  7 2021 10:13:57
BIOS CRC passed (21e99d4b)
Migen git sha1: 3ffd64c
LiteX git sha1: d6084cd1
CPU:		VexRiscv_Lite @ 24MHz
ROM:		32KiB
SRAM:		64KiB
--============== Boot ==================--
Booting from serial...
Press Q or ESC to abort boot completely.
sL5DdSMmkekro
Timeout
No boot medium found
--============= Console ================--
litex> ident
Ident: LiteX SoC on Muselab iCESugar 2021-05-07 11:41:55
```
Flash and load work well.
MusLab LED pmod also works well.
=> muselab_icesugar: first basic version which boots

litex_boards/platforms/qmtech_xc7a35t.py, litex_boards/targets/qmtech_xc7a35t.py
Here are two small fixes for the qmtech board.
=> Qmtech xc7a35t

.gitignore, README.md, litex_boards/platforms/digilent_basys3.py, litex_boards/targets/digilent_basys3.py, test/test_targets.py
The basic board on XC7A35T
Add board info to the repo.
=> Add digilent basys3 board support

litex_boards/platforms/qmtech_ep4ce15.py, litex_boards/targets/qmtech_ep4ce15.py
First application of the daughterboard outside the XC7A35T.
=> QMTech EP4CE15: Add daughterboard support, small DECA addition

litex_boards/platforms/1bitsquared_icebreaker.py
Signed-off-by: Sylvain Munaut <tnt@246tNt.com>
=> icebreaker: Minor fix to usb (add PMOD2 position and fix typo)

litex_boards/platforms/muselab_icesugar_pro.py, litex_boards/targets/muselab_icesugar_pro.py
Add support for muselab_icesugar_pro. It evens boot linux:
Board: https://github.com/wuxx/icesugar-pro
=> muselab_icesugar_pro: initial support

litex_boards/platforms/digilent_cmod_a7.py, litex_boards/platforms/digilent_nexys4.py, litex_boards/platforms/micronova_mercury2.py, litex_boards/targets/digilent_cmod_a7.py, litex_boards/targets/digilent_nexys4.py, litex_boards/targets/micronova_mercury2.py
1.  Digilent CMOD A7
https://reference.digilentinc.com/programmable-logic/cmod-a7/start
2. Digilent Nexys 4
https://reference.digilentinc.com/programmable-logic/nexys-4/start
3. MicroNova Mercury 2
https://www.micro-nova.com/mercury-2
=> add FPGA Boards (Digilent CMOD A7, Digilent Nexys 4, Micronova Mercury2)

litex_boards/targets/kosagi_fomu.py
I've been very excited to see the great work on LiteSPI integration!
Fomu tools support 4 different SPI chips depending on the revision/type of your board (see https://github.com/im-tomu/fomu-flash/blob/c2576a62065b94dc2a47fb7820c8834937ba0343/spi.c#L632-L670). This PR adds support for all of the different ICs based on a keyword argument, while keeping the default as `AT25SF161`. One note is that the `GD25Q16C` currently doesn't support `READ_1_1_4` in LiteSPI.
=> Add option for different Fomu SPI ICs.

README.md
Was very confused when I saw literally no one on freenode :laughing: 
I thought maybe I asked a stupid question and got rbombed for a day
Thanks @tcal-x for pointing me to the correct channel!
=> update IRC channel in README

litex_boards/__init__.py, litex_boards/platforms/tul_pynq_z2.py, litex_boards/targets/tul_pynq_z2.py
Adds support for PYN Z2.
@enjoy-digital zynq7000 CPU support is not tested/working yet.
How did you create the `zybo_z7_ps7.xci` file?
=> WIP: Initial PYNQ Z2 support

litex_boards/platforms/sipeed_tang_nano_4k.py
small correction 100e6 -> 27e6
=> platforms/sipeed_tang_nano_4k: fix period computation

litex_boards/__init__.py, litex_boards/platforms/myminieye_runber.py, litex_boards/targets/myminieye_runber.py
myminieye runber is a Gowin GW1N-4 based board with
- FT232H USB<-> interface
- 8 green leds
- 4 tri leds
- 8 push button
- 8 switch
- 4 seven segments
- two x20 header
Ref:
https://www.seeedstudio.com/Gowin-RUNBER-Development-Board-p-4779.html
=> Add runber support

litex_boards/platforms/digilent_atlys.py, litex_boards/targets/digilent_atlys.py
Added support for the Digilent Atlys board
=> Initial Digilent Atlys support

litex_boards/platforms/antmicro_datacenter_ddr4_test_board.py
=> platforms: ddr4 datacenter: invert eth clocks

litex_boards/platforms/jungle_electronics_fireant.py, litex_boards/targets/jungle_electronics_fireant.py, test/test_targets.py
Thanks to work on Xyloni Dev Kit support done by Andrew Dennison, created board definition for quite similar board with same FPGA on it.
=> FireAnt board support

litex_boards/platforms/sipeed_tang_primer.py, litex_boards/targets/sipeed_tang_primer.py, test/test_targets.py
Since this one use Anlogic toolchain it requires first https://github.com/enjoy-digital/litex/pull/1111 for this to work. 
Due to unknown reasons vexrisc is not working (no response over serial led chaser is working), other cores are doing just fine.
=> Initial support for Sipeed Tang Primer

litex_boards/platforms/spartan_edge_accelerator.py, litex_boards/targets/spartan_edge_accelerator.py
Created a new Spartan Edge Accelerator board. https://www.seeedstudio.com/Spartan-Edge-Accelerator-Board-p-4261.html?gclid=Cj0KCQiA2sqOBhCGARIsAPuPK0hrq-NQxOUmlCJjS-m6wdFDXbhP-a_JoKUqX8sp4p5J4_AOh-k0GnMaAhzLEALw_wcB
=> Spartan Edge Accelerator Board support

litex_boards/platforms/antmicro_datacenter_ddr4_test_board.py, litex_boards/targets/antmicro_datacenter_ddr4_test_board.py
This PR fixes clock pin location and extends eth reset time (required for the ksz9031 phy used on the board)
=> antmicro-datacenter updates

litex_boards/platforms/qmtech_ep4ce55.py, litex_boards/targets/qmtech_ep4ce55.py
The QMTech EP4CE55 board is very similar to the Cyclone IV board already in the repo - but has a much larger and more interesting FPGA.  (It's also used as the core of the Neptuno and UnAmiga Reloaded projects.)
=> Added QMTech EP4CE55 board - almost identical to EP4CE15 board but bigger FPGA

litex_boards/platforms/digilent_cmod_a7.py, litex_boards/targets/digilent_cmod_a7.py
Meaning, that it fixed the build with symbiflow.
=> Digilent cmod a7: Fix litex build.

litex_boards/targets/digilent_nexys_video.py
allow SATA gen argument to be specified via command line
=> targets/digilent_nexys_video: add SATA generation argument

litex_boards/targets/quicklogic_quickfeather.py
Similar to https://github.com/litex-hub/litex-boards/pull/322 but with `libeos` as a github archive until we figure out the best way to integrate this.
=> quicklogic_quickfeather: add eos_s3 arm software support library

litex_boards/platforms/digilent_cmod_a7.py, litex_boards/targets/digilent_cmod_a7.py
Signed-off-by: Tim Callahan <tcal@google.com>
=> Add openocd programmer for Digilent CMOD A7.

litex_boards/platforms/sipeed_tang_nano_9k.py, litex_boards/targets/sipeed_tang_nano_9k.py
Also enable SPI SDCard which was pending by the lack of main_ram
previously.
Signed-off-by: Icenowy Zheng <icenowy@aosc.io>
-----------------------------------
Depends on https://github.com/enjoy-digital/litex/pull/1176
=> sipeed_tang_nano_9k: enable copackaged PSRAM

litex_boards/platforms/terasic_deca.py, litex_boards/targets/terasic_deca.py
Based on top of #341 and #342.
=> DECA: Add Ethernet and Etherbone support

litex_boards/platforms/lattice_ecp5_vip.py, litex_boards/targets/lattice_ecp5_vip.py
WIP: will do some cleanup soon
Let me know if there is something more like code style or something else I need to fix.
Thanks
https://twitter.com/hubmartin/status/1490430338266451975
=> Draft: Add Lattice ECP5 VIP board + HDMI output board support

litex_boards/platforms/xilinx_zcu216.py, litex_boards/targets/xilinx_zcu216.py
Very similar in all ways to KV260 - BIOS runs on Cortex-A53 core #0, Wishbone <-> AXI works to control LEDs in the logic.
=> Add Xilinx ZCU216 support

litex_boards/platforms/adi_adrv2crr_fmc.py
I had never tried to use some of the devices that were on the board. Attempting to do so today showed some mistakes in the platform file.
=> ADRV2CRR: Fixing some of my screwups that I just noticed now

README.md, litex_boards/__init__.py, litex_boards/platforms/arduino_mkrvidor4000.py, litex_boards/targets/arduino_mkrvidor4000.py
Device target and board files. It is still work in progress, and in a somewhat rough state but it produces a working SoC and bios and might be useful for someone else already. See also my litedram PR.
=> Board support for Arduino MKR Vidor 4000

CONTRIBUTORS, README.md, litex_boards/platforms/u420t.py, litex_boards/targets/u420t.py
Added Kintex-7 xc7k420t xc7k420tiffg901-2L named as u420t fpga board.
verified
=> Added Kintex-7 xc7k420t xc7k420tiffg901-2L named as u420t board

litex_boards/platforms/qmtech_ep4cgx150.py, litex_boards/targets/qmtech_ep4cgx150.py
This board is fabulous value for money. 150kLUTS for $80!
```
(c) Copyright 2012-2022 Enjoy-Digital
BIOS built on Apr 16 2022 06:32:35
BIOS CRC passed (d851280f)
LiteX git sha1: 3dbe349d
CPU:		VexRiscv @ 50MHz
ROM:		128KiB
SRAM:		8KiB
L2:		8KiB
SDRAM:		32768KiB 16-bit @ 50MT/s (CL-2 CWL-2)
Read: 0x40000000-0x40200000 2.0MiB …
```
=> add board support for QMTech EP4CGX150

litex_boards/platforms/sipeed_tang_primer_20k.py, litex_boards/targets/sipeed_tang_primer_20k.py
Only initial support is added.
Signed-off-by: Icenowy Zheng <uwu@icenowy.me>
=> sipeed_tang_primer_20k: new board

litex_boards/platforms/a_e115fb.py, litex_boards/targets/a_e115fb.py
It's a core board with EP4CE115 by a random vendor on Taobao.
Signed-off-by: Icenowy Zheng <uwu@icenowy.me>
=> a_e115fb: new board

litex_boards/platforms/qmtech_xc7a35t.py, litex_boards/platforms/quicklogic_quickfeather.py
Related to [#1334](https://github.com/enjoy-digital/litex/pull/1334).
=> Move from deprecated Symbiflow to F4PGA

litex_boards/targets/icebreaker_bitsy.py
Currently, building icebreaker_bitsy with --uart-name usb_acm does not work.
Here we instantiate the PLL to create the two clocks required by valentyusb and force sys_clk to 48MHz, if usb_acm is selected.
tested on v1.1 hardware with:
```python
python litex_boards/targets/icebreaker_bitsy.py --cpu-type serv --build --flash --csr-csv build/icebreaker_bitsy/csr.csv --uart-name usb_acm
python litex_boards/targets/icebreaker_bitsy.py --cpu-type serv --build --flash --csr-csv build/icebreaker_bitsy/csr.csv --uart-name serial --sys-clk-freq 60e6
```
=> [fix] instanciate PLL for valentyUSB

litex_boards/platforms/antmicro_artix_dc_scm.py, litex_boards/targets/antmicro_artix_dc_scm.py
Based on commits by:
- Jedrzej Boczar <jboczar@antmicro.com>
- Karol Gugala <kgugala@antmicro.com>
Tested serial and networking on a DC-SCM with mor1k and vexriscv.
=> Add Antmicro Artix DC-SCM board

litex_boards/platforms/qmtech_ep4ce15_starter_kit.py, litex_boards/targets/qmtech_ep4ce15_starter_kit.py
This board: https://fr.aliexpress.com/i/33007471265.html?gatewayAdapt=glo2fra
=> Add qmtech Cyclone IV Starter Kit

litex_boards/targets/digilent_arty_z7.py
This PR adds the `finalize` method to fetch **embeddedsw** repository, fills `xparameters.h` (used to provides UART to use and RAM size). These steps are required to build the **litex bios** for this board.
Tested with **xcst**:
```
xsct -nodisp ps7_boot.tcl \
$PS7_INIT_TCL $MAIN_ELF $BIT_FILE
```
where:
- `PS7_INIT_TCL`: the ps7_init.tcl: *build/TARGET/gateware/TARGET.srcs/sources_1/ip/TARGET/ps7_init.tcl*
- `MAIN_ELF`: the bios file
- `BIT_FILE`: the bitstream
ps7_boot.tcl contains:
```
connect
targets -set -filter {name =~ "ARM*#0"}
rst
stop
source [lindex $argv 0]
ps7_init
ps7_post_config
dow [lindex $argv 1]
fpga [lindex $argv 2]
con
```
Side note:
- maybe adding an arg to disable the **bios** build when user want to use bootloader+linux instead of baremetal
- code added by this PR …
=> targets/digilent_arty_z7: adding software support

litex_boards/targets/isx_im1283.py
- Add Jtagbone support.
- Add soft reset support.
=> Some small enhancements to iSX iM1283

README.md, litex_boards/platforms/machdyne_konfekt.py, litex_boards/platforms/machdyne_noir.py, litex_boards/targets/machdyne_konfekt.py, litex_boards/targets/machdyne_noir.py
This adds support for the Machdyne Konfekt FPGA computer (SDRAM) and the Machdyne Noir FPGA computer (DDR3L).
https://github.com/machdyne/konfekt
https://github.com/machdyne/noir
=> initial support for machdyne konfekt and noir

litex_boards/platforms/antmicro_sdi_mipi_video_converter.py, litex_boards/targets/antmicro_sdi_mipi_video_converter.py
This PR adds target and platform for Antmicro's open-source [SDI-MIPI Video Converter](https://github.com/antmicro/sdi-mipi-video-converter).
=> Add support for SDI-MIPI Video Converter

README.md, litex_boards/platforms/machdyne_kopflos.py, litex_boards/targets/machdyne_kopflos.py
Hi. This PR adds support for the [Kopflos](https://github.com/machdyne/kopflos) headless FPGA computer.
Please note that Ethernet support relies on a pending PR in liteeth: https://github.com/enjoy-digital/liteeth/pull/126
=> add support for machdyne kopflos board

litex_boards/targets/digilent_nexys_video.py
Make nexys-video SATA configuration similar to the way it is supported on the majority of other SATA-capable targets.
=> targets/nexys-video: simplify sata configuration

litex_boards/platforms/qmtech_5cefa5.py, litex_boards/targets/qmtech_5cefa5.py
```
(c) Copyright 2012-2023 Enjoy-Digital
BIOS built on Apr  6 2023 18:15:13
BIOS CRC passed (2e3ad37f)
LiteX git sha1: 0c326f0e
CPU:		VexRiscv @ 80MHz
ROM:		128.0KiB
SRAM:		8.0KiB
L2:		8.0KiB
SDRAM:		64.0MiB 32-bit @ 80MT/s (CL-2 CWL-2)
MAIN-RAM:	64.0MiB
Read: 0x40000000-0x40200000 2.0MiB     
Memtest OK
Memspeed at 0x40000000 (Sequential, 2.0MiB)... …
```
=> add QMTech 5CEFA5 Cyclone V board support

litex_boards/platforms/terasic_de10nano.py
=> Corrected DE10-Nano Pin Number

litex_boards/platforms/qmtech_daughterboard.py, litex_boards/platforms/qmtech_xc7k325t.py, litex_boards/targets/qmtech_xc7k325t.py
I actually have forgot to contribute this one.
It actually think this has been originally written by @kazkojima , which he has shared with me.
I modified this a bit.
Have not tested in its current form,
but the LiteX build runs fine.
=> Add QMTech XC7K325T

litex_boards/platforms/xilinx_vcu128.py, litex_boards/targets/xilinx_vcu128.py
DDR4, HBM2 and uart are tested.
The pr depends on https://github.com/enjoy-digital/litedram/pull/332 and https://github.com/enjoy-digital/litex/pull/1673 to work.
=> Add vcu128 target

litex_boards/targets/colorlight_5a_75x.py
The pins have been mapped for the SPI flash on most variants of these boards, so this just adds `--with-spi-flash` mapped to `0x20000000` as an option for generating the SoC. This has only been tested with a 5A-75B V7.0 -- the rest of the variants have been extrapolated from available documentation.
=> Support SPI Flash in Colorlight 5A-75x

.github/dependabot.yml, .github/workflows/ci.yml, setup.py
- Add version number
- include readme as long description
- add explicit litex dependency
- use github action for python install
- add dependabot action upgrader
- update checkout action
=> Small packaging and CI improvements

README.md, litex_boards/platforms/machdyne_mozart_ml1.py, litex_boards/targets/machdyne_mozart_ml1.py
This PR adds support for Mozart with the Sechzig ML1 module.
https://github.com/machdyne/mozart
https://github.com/machdyne/sechzig
=> add support for mozart ml1

litex_boards/platforms/alinx_axau15.py, litex_boards/targets/alinx_axau15.py
https://alinx.com/en/detail/691
Docs: https://alinx.com/public/upload/file/AXAU15_UG.pdf
English Docs: https://file.io/w0Kc2qJPkABm
=> alinx_axau15: Added new Alinx Artix US+ board

README.md, litex_boards/platforms/machdyne_minze.py, litex_boards/targets/machdyne_minze.py
This PR adds support for the Minze FPGA computer:
https://github.com/machdyne/minze
=> add support for minze board

README.md, litex_boards/platforms/qmtech_kintex7_devboard.py, litex_boards/targets/qmtech_kintex7_devboard.py
This pull request adds support for the QMTech Kintex 7 Development board (Kintex 7 with on-board header for Raspberry Pi Compute Module 4).
=> Add support for QMTech Kintex 7 Development board

litex_boards/platforms/colognechip_gatemate_evb.py, litex_boards/targets/colognechip_gatemate_evb.py, test/test_targets.py
Tested with a rev V3.1B and a vexriscv CPU
=> adding colognechip_gatemate_evb

litex_boards/platforms/alientek_davincipro.py
One dash slipped in there somehow.
=> alientek_davincipro: fix part number

litex_boards/platforms/qmtech_artix7_fgg676.py
I just encountered a 200T variant of this board in the wild.
Which means it exists.
A MiSTeX user has it.
=> qmtech_artix7_fgg676.py: This board also has a 200T variant

litex_boards/platforms/hseda_xc7a35t.py, litex_boards/targets/hseda_xc7a35t.py
Add HSEDA XC7A35T board support
=> Add HSEDA XC7A35T board support

litex_boards/targets/efinix_trion_t20_bga256_dev_kit.py
to do a reset on the efinix trion t20 a pulse is needed. 
See https://www.efinixinc.com/docs/an046-reset-guidelines-efinix-fpga-v1.1.pdf
=> targets: efinix_trion_t20_bga256_dev_kit: add pulse for reset

README.md, litex_boards/platforms/lattice_certuspro_nx_evn.py, litex_boards/platforms/lattice_certuspro_nx_vvml.py, litex_boards/targets/lattice_certuspro_nx_evn.py, litex_boards/targets/lattice_certuspro_nx_vvml.py
Support for:
- [lattice_certuspro_nx_evn](https://www.latticesemi.com/products/developmentboardsandkits/certuspro-nxevaluationboard)
- [lattice_certuspro_nx_vvml](https://www.latticesemi.com/certuspro-nx-vvml-board)
=> Lattice certusnxpro

litex_boards/platforms/sipeed_tang_mega_138k_pro.py, litex_boards/platforms/sipeed_tang_primer_25k.py, litex_boards/targets/sipeed_tang_mega_138k_pro.py, litex_boards/targets/sipeed_tang_primer_25k.py
This PR adress both @sipeed Tang Primer 25k and Tang Mega 138k pro:
- for both boards, user may select between mister SDRAM and sipeed SDRAM extensions
- for Mega it adds SDRAM module present on sipeed extension
- for Primer it adds SDRAM support
=> Sipeed tang gw5 a sdram

litex_boards/targets/efinix_titanium_ti60_f225_dev_kit.py
Tested at up to 250MHz sys_clk -> 125MHz HyperRAM Clk.
Requires https://github.com/enjoy-digital/litex/pull/2053.
=> ti60_f225_dev_kit: Update to new HyperRAM core with 2:1 ratio.

litex_boards/targets/trenz_tec0117.py
Similar to the recent Tang Nano changes.
Also makes CLKDIV optional if using 1:1 SDRAM rate and fixes the bios flashing.
=> Update tec0117 to work with Apicula

README.md, litex_boards/platforms/machdyne_mozart_mx2.py, litex_boards/targets/machdyne_mozart_mx2.py
This PR adds support for [Sechzig MX2](https://github.com/machdyne/sechzig) on [Mozart](https://github.com/machdyne/mozart).
=> add support for Mozart MX2

litex_boards/platforms/trenz_te0890.py, litex_boards/targets/trenz_te0890.py
Add a platform and target for the Trenz S7 Mini (aka TE0890).
=> Add support for S7 Mini (TE0890).

litex_boards/platforms/sipeed_tang_nano_20k.py
This pull request adds the pinout for some of the hdmi connector, and the two rows of pins on the board.
=> Add hdmi conector to tang nano 20k and connector pinout.

litex_boards/platforms/efinix_ti375_c529_dev_kit.py, litex_boards/targets/efinix_ti375_c529_dev_kit.py
add ethernet/etherbone support for efinix_ti375_c529_dev_kit.
Signed-off-by: Fin Maaß <f.maass@vogl-electronic.com>
=> efinix_ti375_c529_dev_kit: add ethernet/etherbone support 

litex_boards/platforms/colorlight_5a_75e.py
Added v8.2 board of Colorlight 5A-75E
=> Add colorlight 5A-75E v8.2 board

litex_boards/targets/sipeed_tang_mega_138k_pro.py
This PR adds support for PCIe via LitePCIe GW5APCIEPHY Module.
It depends on [LitePCIe PR](https://github.com/enjoy-digital/litepcie/pull/142)
- tested on PCIe x4: MMAP access and MSI are working.
- the PHY via the code generated by Gowin's IP Core Generator is configured for 8GT/s Gen3 but lspci reports 2.5-5GTs in its capabilities (maybe something related to the hardware and/or FPGA: ES model).
=> targets/sipeed_tang_mega_138k_pro.py: added PCIe support

litex_boards/platforms/sqrl_acorn.py
Ref : https://github.com/enjoy-digital/litex-acorn-baseboard/blob/master/hardware/acorn.pdf
=> Fix SFP-1 pin on sqrl_acorn.py

litex_boards/targets/digilent_zedboard.py
Note: It's a WIP, don't merge.
Zynq devices are supported (of course) by Vivado but also by f4pga, yosys+nextpnr and openxc7.
This PR honour toolchain argument to let the user selects toolchain.
**Note:**
- Needs to test if zynq7000 SoC is supported, currently this option is only allowed with *Vivado*
- USART is disabled, and an external UART interface must be added.
For [openxc7](https://github.com/openxc7) follows [toolchain-installer](https://github.com/openXC7/toolchain-installer).
To build gateware, this command do the job
```bash
cd litex-boards/litex_boards/targets
export CHIPDB=/somewhere
./digilent_zedboard.py --build --toolchain openxc7 --cpu-type vexriscv
```
=> targets/digilent_zedboard.py: honour toolchain argument.

litex_boards/targets/efinix_ti375_c529_dev_kit.py
add sfp
only for trying sfp, not for merge, would break other things.
=> ti375_c529: WIP: add SFP

litex_boards/platforms/olimex_gatemate_a1_evb.py, litex_boards/targets/olimex_gatemate_a1_evb.py
This one requires https://github.com/enjoy-digital/litex/pull/2248 to be able to generate code
=> olimex_gatemate_a1_evb: Added Ethernet and SD card interface

litex_boards/platforms/colognechip_gatemate_evb.py, litex_boards/targets/colognechip_gatemate_evb.py
This PR fixes pin mapping for SPI and adds flash support.
Note: requires https://github.com/enjoy-digital/litex/pull/2249
=> colognechip_gatemate_evb:  SPI flash support

litex_boards/targets/colognechip_gatemate_evb.py
This PR adds HyperRAM support has default `main_ram` Region.
=> targets/colognechip_gatemate_evb.py: added HyperRAM support

litex_boards/platforms/digilent_nexys_video.py, litex_boards/targets/digilent_nexys_video.py
Using PMOD connector JB supporting a PMOD like : https://github.com/nand2mario/usb_host_pmod
=> Add USB-OHCI functionality similar to what is on the digilent_arty to the nexsys_video board

litex_boards/platforms/efinix_tz170_j484_dev_kit.py, litex_boards/targets/efinix_tz170_j484_dev_kit.py, test/test_targets.py
add tz170_j484_dev_kit
Signed-off-by: Fin Maaß <f.maass@vogl-electronic.com>
=> boards: efinix:  add tz170_j484_dev_kit

README.md, litex_boards/platforms/icepi_zero.py, litex_boards/targets/icepi_zero.py
I've added support for the Icepi Zero, my ECP5 FPGA board that will be shipped out in a few months :) (https://www.crowdsupply.com/icy-electronics/icepi-zero/)
=> Add support for Icepi Zero
